bracketing and quoting vars

diff --git a/barcodeinterpret b/barcodeinterpret
--- a/barcodeinterpret
+++ b/barcodeinterpret
@@ -1,8 +1,8 @@
 #!/bin/bash
 # interpret Interleaved 2/5 barcode 58 byte barcode values used by the ProBell tape management system
 
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 
 cleanup(){
     _log -a "Process aborted"
@@ -16,7 +16,7 @@ if test $# != 1 ; then
     echo "You must supply one argument, a scanned interleaved 2/5 barcode value"; exit
 fi
 
-barcode="$1"
+barcode="${1}"
 
 translatebyte()
 {
diff --git a/blackatends b/blackatends
--- a/blackatends
+++ b/blackatends
@@ -1,8 +1,8 @@
 #!/bin/bash
 # blackatends
 # Accepts one or many video files as an input and determines how many frames of black are at the beginning and at the end
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 version=1.0
 
 cleanup(){
@@ -14,7 +14,7 @@ trap cleanup SIGHUP SIGINT SIGTERM
 
 usage(){
     echo
-    echo "$(basename "$0") ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This program will report on the number of black frames at the beginning and end of a video file."
     echo
     echo "Usage: $(basename $0) file1 [ file2 ... ]"
@@ -37,9 +37,9 @@ while getopts ":h" opt; do
 done
 shift $(( ${OPTIND} - 1 ))
 
-while [ "$*" != "" ] ; do
+while [ "${*}" != "" ] ; do
     _log -b
-    [ "$#" != 0 ] && sourcefile="$1"
+    [ "$#" != 0 ] && sourcefile="${1}"
     black_at_ends "$sourcefile"
     _log -e
     shift
diff --git a/makebroadcast b/makebroadcast
--- a/makebroadcast
+++ b/makebroadcast
@@ -4,17 +4,17 @@
 # v 1.2 revert to mov and ffmbc
 # v 1.3 revert back to ffmpeg
 version="1.3"
-scriptdir=$(dirname $(which "$0"))
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname $(which "${0}"))
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 dependencies=(ffmpeg ffprobe)
 _initialize_make
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will create a file suitable for broadcast or editing from a video file or package input with the following options."
     echo "Dependencies: ${dependencies[@]}"
-    echo "Usage: $(basename ${0}) [ -l ] [ -r ] [ -c ] fileorpackage1 [ fileorpackage2 ...]"
+    echo "Usage: $(basename "${0}") [ -l ] [ -r ] [ -c ] fileorpackage1 [ fileorpackage2 ...]"
     echo "  -F (apply a formula, override default settings)"
     echo "  -l (only use the left channel of the first audio track)"
     echo "  -r (only use the right channel of the first audio track)"
@@ -54,7 +54,7 @@ shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="$1"
+    input="${1}"
     if [ -z "${outputdir_forced}" ] ; then
         [ -d "${input}" ] && { outputdir="${input}/objects/service" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
         [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/service" && logdir="$(dirname "${input}")/service/logs" ;};
diff --git a/makedvd b/makedvd
--- a/makedvd
+++ b/makedvd
@@ -1,14 +1,14 @@
 #!/bin/bash
 # makedvd
 version="1.0"
-scriptdir=$(dirname $(which "$0"))
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname $(which "${0}"))
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 dependencies=(ffmpeg dvdauthor mkisofs)
 _initialize_make
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will create a DVD .iso file from a video file or package input with the following options."
     echo "Dependencies: ${dependencies[@]}"
     echo "Usage: $(basename $0) [ -v dvd_label_prefix ] fileorpackage1 [ fileorpackage2 ...]"
@@ -48,7 +48,7 @@ shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="$1"
+    input="${1}"
     if [ -z "${outputdir_forced}" ] ; then
         [ -d "${input}" ] && { outputdir="${input}/objects/access/dvd" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
         [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/access/dvd" && logdir="$(dirname "${input}")/access/logs" ;};
diff --git a/makeframes b/makeframes
--- a/makeframes
+++ b/makeframes
@@ -1,8 +1,8 @@
 #!/bin/bash
 # makeframes
 version="1.0"
-scriptdir=$(dirname $(which "$0"))
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname $(which "${0}"))
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 dependencies=(ffmpeg)
 _initialize_make
 
@@ -11,7 +11,7 @@ IMAGECOUNT=10
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will create a series of still images from a video file or package input with the following options."
     echo "Dependencies: ${dependencies[@]}"
     echo "Usage: $(basename $0) [ -d /path/to/deliver/to/ ] fileorpackage1 [ fileorpackage2 ...]"
@@ -38,14 +38,14 @@ while getopts ":d:e:E:nh" opt ; do
 done
 shift $(( ${OPTIND} - 1 ))
 
-while [ "$*" != "" ] ; do
-    input="$1"
+while [ "${*}" != "" ] ; do
+    input="${1}"
     [ -d "$input" ] && { outputdir="$input/objects/access/images" && logdir="$input/metadata/submissionDocumentation/logs" ;};
     [ -f "$input" ] && { outputdir=$(dirname "$input")"/access/images" && logdir="$(dirname "$input")/access/logs" ;};
     [ ! "$outputdir" ] && { outputdir="$input/objects/access/images" && logdir="$input/metadata/submissionDocumentation/logs" ;};
     _find_input "$input"
 
-    mediaid=$(basename "$1" | cut -d. -f1)
+    mediaid=$(basename "${1}" | cut -d. -f1)
 
     # clear local arrays
     unset inputoptions
diff --git a/makelossless b/makelossless
--- a/makelossless
+++ b/makelossless
@@ -1,14 +1,14 @@
 #!/bin/bash
 # makelossless
 version="1.0"
-scriptdir=$(dirname $(which "$0"))
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname $(which "${0}"))
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 dependencies=(ffmpeg mediainfo)
 _initialize_make
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will losslessly transcode a video file or package input with the following options."
     echo "Dependencies: ${dependencies[@]}"
     echo "Usage: $(basename $0) fileorpackage1 [ fileorpackage2 ...]"
@@ -35,7 +35,7 @@ shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="$1"
+    input="${1}"
     [ -d "${input}" ] && logdir="${input}/metadata/submissionDocumentation/logs"
     [ -f "${input}" ] && logdir="$(dirname "${input}")/lossless/logs"
     [ ! "${logdir}" ] && logdir="${input}/metadata/submissionDocumentation/logs"
diff --git a/makepdf b/makepdf
--- a/makepdf
+++ b/makepdf
@@ -1,8 +1,8 @@
 #!/bin/bash
 # makepdf, makes a pdf from an image series
 version="1.0"
-scriptdir=$(dirname $(which "$0"))
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname $(which "${0}"))
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 dependencies=(ffmpeg convert pdfjoin tesseract)
 _initialize_make
 
@@ -37,7 +37,7 @@ check_tif_name(){
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will create a small pdf file (suitable for sharing online) from a collection of image file or package input with the following options."
     echo "Dependencies: ${dependencies[@]}"
     echo "Usage: $(basename $0) [ -d /path/to/deliver/to/ ] fileorpackage1 [ fileorpackage2 ...]"
@@ -73,7 +73,7 @@ shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="$1"
+    input="${1}"
     if [ -z "${outputdir_forced}" ] ; then
         [ -d "${input}" ] && { outputdir="${input}/objects/access/pdf_1" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
         [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/access/pdf_1" && logdir="$(dirname "${input}")/access/logs" ;};
diff --git a/makeprores b/makeprores
--- a/makeprores
+++ b/makeprores
@@ -1,8 +1,8 @@
 #!/bin/bash
 # makeprores, makes a file appropriate for keeping editors happy
 version="1.0"
-scriptdir=$(dirname $(which "$0"))
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname $(which "${0}"))
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 dependencies=(ffmpeg)
 _initialize_make
 
@@ -10,7 +10,7 @@ outputdir="$HOME/Desktop/$(basename $0)" # default output directory, override wi
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will create a prores/quicktime file (suitable for editing) from a video file or package input with the following options. By default the output will be written to ${outputdir}. You can override this with the -o option."
     echo "Dependencies: ${dependencies[@]}"
     echo "Usage: $(basename $0) [ -o /directory/to/write/to/ ] fileorpackage1 [ fileorpackage2 ...]"
@@ -43,7 +43,7 @@ shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="$1"
+    input="${1}"
     if [ -z "${outputdir_forced}" ] ; then
         [ -d "${input}" ] && { outputdir="${input}/objects/access/prores" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
         [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/access/prores" && logdir="$(dirname "${input}")/access/logs" ;};
diff --git a/makeyoutube b/makeyoutube
--- a/makeyoutube
+++ b/makeyoutube
@@ -1,14 +1,14 @@
 #!/bin/bash
 # makeyoutube, makes a file appropriate for uploading to youtube
 version="1.0"
-scriptdir=$(dirname $(which "$0"))
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname $(which "${0}"))
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 dependencies=(ffmpeg)
 _initialize_make
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will create a high quality h264 file (suitable for uploading to YouTube) from a video file or package input with the following options."
     echo "Dependencies: ${dependencies[@]}"
     echo "Usage: $(basename $0) [ -d /path/to/deliver/to/ ] fileorpackage1 [ fileorpackage2 ...]"
@@ -48,7 +48,7 @@ shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="$1"
+    input="${1}"
     if [ -z "${outputdir_forced}" ] ; then
         [ -d "${input}" ] && { outputdir="${input}/objects/access/youtube_up" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
         [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/access/youtube_up" && logdir="$(dirname "${input}")/access/logs" ;};
diff --git a/mmconfig b/mmconfig
--- a/mmconfig
+++ b/mmconfig
@@ -3,14 +3,14 @@
 # set up variables for microservices
 CONFIG="Y"
 CONFIG_VERSION="1.0"
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 
 # local variables
 REQUIRED_VARIABLES=("OUTDIR_INGESTFILE" "OUTDIR_INGESTXDCAM" "OUTDIR_PAPER" "AIP_STORAGE" "PODCASTDELIVER" "YOUTUBEDELIVER" "TMPDIR" "REGEX4PODCAST" "DVDLABELPREFIX" "OMNEONIP" "OMNEONPATH" "CUSTOM_LOG_DIR" "LTO_INDEX_DIR" "LOCAL_MM_DIR" "EMAIL_FROM" "MAKEYOUTUBE_DELIVERY_EMAIL_TO" "MAKEBROADCAST_DELIVERY_EMAIL_TO" "FILEMAKER_DB" "FILEMAKER_XML_URL")
 
 config_edit(){
-    [ -z "$1" -o -z "$2" ] && { report -w "The config_edit function requires two arguments. Error." ; exit ;};
+    [ -z "${1}" -o -z "$2" ] && { report -w "The config_edit function requires two arguments. Error." ; exit ;};
     sedtemp=$(maketemp)
     sed "s:^$1=[^ ]*:$1=$2:" "$CONFIG_FILE" > "$sedtemp"
     cp "$sedtemp" "$CONFIG_FILE"
@@ -27,7 +27,7 @@ test_config(){
 }
 
 add_key(){
-    key_to_add="$1"
+    key_to_add="${1}"
     grep -q "^$key_to_add=" "$CONFIG_FILE" ; grep_code="$?"
     if [[ ! "${grep_code}" -eq "0" ]] ; then
         report -td "Adding NEW variable $key_to_add to $CONFIG_FILE"
diff --git a/removeDSStore b/removeDSStore
--- a/removeDSStore
+++ b/removeDSStore
@@ -1,8 +1,8 @@
 #!/bin/bash
 # @author Dave Rice
 
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 
 cleanup(){
     _log -a "Process aborted"
@@ -12,7 +12,7 @@ cleanup(){
 trap cleanup SIGHUP SIGINT SIGTERM
 _log -b
 
-while [ "$*" != "" ] ; do
+while [ "${*}" != "" ] ; do
     target=$1
     if [ -d "$target" ]; then
         find "$target" -name '.DS_Store' -type f -delete
diff --git a/uploadomneon b/uploadomneon
--- a/uploadomneon
+++ b/uploadomneon
@@ -5,12 +5,12 @@ requireconfig="Y"
 
 version="1.0"
 
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This application will upload file(s) to a server via rsync in sequential order. Options are specified via 'mmconfig'."
     echo
     echo "Settings:"
@@ -30,7 +30,7 @@ cleanup(){
 }
 
 get_ftp_status(){
-local filename="$1"
+local filename="${1}"
 status=$(ftp -a "$OMNEONIP" <<END_SCRIPT
 binary
 ls "${OMNEONPATH}/${filename}"
@@ -58,9 +58,9 @@ shift $(( ${OPTIND} - 1 ))
 [ ! -n "$OMNEONIP" ] && { report -wt "The Omneon IP must be set. Run 'mmconfig'." ; exit 1 ;};
 [ ! -n "$OMNEONPATH" ] && { report -wt "The Omneon Path must be set. Run 'mmconfig'." ; exit 1 ;};
 
-while [ "$*" != "" ] ; do
+while [ "${*}" != "" ] ; do
 
-sourcefile="$1"
+sourcefile="${1}"
 extension=$(echo "$sourcefile" |awk -F . '{print $NF}')
 if [ "$extension" == "mov" -o "$extension" == "mxf" ] ; then
 
diff --git a/verifypackage b/verifypackage
--- a/verifypackage
+++ b/verifypackage
@@ -4,8 +4,8 @@ version="1.0"
 unset dependencies
 dependencies=(ffmpeg mediainfo)
 
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 
 usage(){
     echo
@@ -37,10 +37,10 @@ while getopts ":ho:n" opt; do
 done
 shift $(( ${OPTIND} - 1 ))
 
-while [ "$*" != "" ] ; do
-    package="$1"
+while [ "${*}" != "" ] ; do
+    package="${1}"
     find_input "$input"
-    mediaid=$(basename "$1" | cut -d. -f1)
+    mediaid=$(basename "${1}" | cut -d. -f1)
 
     log -b
 
diff --git a/xdcamingest b/xdcamingest
--- a/xdcamingest
+++ b/xdcamingest
@@ -3,8 +3,8 @@
 # ingest an xdcam disc, make a package, and deliver select files
 requireconfig="Y"
 
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 
 cleanup(){
     _log -a "Process aborted"
@@ -16,7 +16,7 @@ _log -b
 
 usage(){
     echo
-    echo "$(basename ${0}) ${version}"
+    echo "$(basename "${0}") ${version}"
     echo "This script may be run interactively by running it with no arguments or may be used with the following options."
     echo "Usage: $(basename $0) [ -c output_directory_for_xdcam ]"
     echo "  -c output_directory_for_xdcam (else will default to $CONFIG_FILE)"
