Standardized variables and functions across all mm scripts.

diff --git a/blackatends b/blackatends
--- a/blackatends
+++ b/blackatends
@@ -1,46 +1,46 @@
 #!/bin/bash
 # blackatends
 # Accepts one or many video files as an input and determines how many frames of black are at the beginning and at the end
-scriptdir=$(dirname "${0}")
-. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
-version=1.0
+SCRIPTDIR=$(dirname "${0}")
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
+VERSION=1.0
 
-cleanup(){
+_cleanup(){
     _log -a "Process aborted"
     exit 1
 }
 
-trap cleanup SIGHUP SIGINT SIGTERM
+trap _cleanup SIGHUP SIGINT SIGTERM
 
-usage(){
+_usage(){
     echo
-    echo "$(basename "${0}") ${version}"
+    echo "$(basename "${0}") ${VERSION}"
     echo "This program will report on the number of black frames at the beginning and end of a video file."
     echo
-    echo "Usage: $(basename $0) file1 [ file2 ... ]"
+    echo "Usage: $(basename ${0}) file1 [ file2 ... ]"
     echo
     echo "Options:"
     echo "  -h display this help"
     echo
     exit
 }
-[ "$#" = 0 ] && usage
+[ "${#}" = 0 ] && _usage
 
 # command-line options to set mediaid and original variables
 OPTIND=1
-while getopts ":h" opt; do
-    case "$opt" in
-        h) usage ;;
-        \?) echo "Invalid option: -$OPTARG" ; exit 1 ;;
-        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
+while getopts ":h" OPT; do
+    case "${OPT}" in
+        h) _usage ;;
+        \?) echo "Invalid option: -${OPTARG}" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     _log -b
-    [ "$#" != 0 ] && sourcefile="${1}"
-    black_at_ends "$sourcefile"
+    [ "${#}" != 0 ] && SOURCEFILE="${1}"
+    _black_at_ends "${SOURCEFILE}"
     _log -e
     shift
 done
diff --git a/fix_volume b/fix_volume
--- a/fix_volume
+++ b/fix_volume
@@ -1,82 +1,82 @@
 #!/bin/bash
 # this script takes one argument which is a video file. It evaluates the audio of the file, determines the difference needed to change the audio to -30dB as a mean_volume and then makes that adjustment to an output MXF file. The video track is simply copied.
 # version 1.1 swap from ffmbc to ffmpeg
-version=1.1
-unset dependencies
-dependencies=(ffmpeg ffprobe)
+VERSION=1.1
+unset DEPENDENCIES
+DEPENDENCIES=(ffmpeg ffprobe)
 
 # local variables
-suffix="_voladj"
+SUFFIX="_voladj"
 
-scriptdir=$(dirname "${0}")
-. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
+SCRIPTDIR=$(dirname "${0}")
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
 
-usage(){
+_usage(){
     echo
-    echo "$(basename "${0}") ${version}"
-    echo "This application will use an input video file to produce an output video file where the audio is adjusted to meet an integrated loudness of -23dB. If the integrated loudness of the input is already within 1dB of the target then no change will occur. The output file will be produced in the same directory as the input but be distinguished by a suffix in the filename: ${suffix}."
-    echo "Dependencies: ${dependencies[@]}"
+    echo "$(basename "${0}") ${VERSION}"
+    echo "This application will use an input video file to produce an output video file where the audio is adjusted to meet an integrated loudness of -23dB. If the integrated loudness of the input is already within 1dB of the target then no change will occur. The output file will be produced in the same directory as the input but be distinguished by a SUFFIX in the filename: ${SUFFIX}."
+    echo "Dependencies: ${DEPENDENCIES[@]}"
     echo "Usage: $(basename "${0}") file1 [ file2 ...]"
     echo "  -h display this help"
     echo
     exit
 }
-[ "${#}" = 0 ] && usage
-check_dependencies "${dependencies[@]}"
+[ "${#}" = 0 ] && _usage
+_check_dependencies "${DEPENDENCIES[@]}"
 
 # command line arguments
 OPTIND=1
-while getopts ":h" opt ; do
-    case ${opt} in
-        h) usage ;;
+while getopts ":h" OPT ; do
+    case "${OPT}" in
+        h) _usage ;;
         *) echo "Invalid option: -${OPTARG}" ; exit 1 ;;
         :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
 
-cleanup(){
+_cleanup(){
     _log -a "Process aborted"
     exit 1
 }
 
-trap cleanup SIGHUP SIGINT SIGTERM
+trap _cleanup SIGHUP SIGINT SIGTERM
 _log -b
 
 while [ "${*}" != "" ] ; do
-    sourcefile="${1}"
-    name=$(basename "${sourcefile}")
-    extension="${name#*.}"
+    SOURCEFILE="${1}"
+    NAME=$(basename "${SOURCEFILE}")
+    EXTENSION="${NAME#*.}"
 
-    get_codectagstring
-    unset middleoptions
-    middleoptions+=(-map 0:v)
-    middleoptions+=(-c:v copy)
-    middleoptions+=(-map 0:a)
-    middleoptions+=(-c:a pcm_s24be)
-    middleoptions+=(-ar 48000)
-    middleoptions+=(-ac 2)
+    _get_codectagstring
+    unset MIDDLEOPTIONS
+    MIDDLEOPTIONS+=(-map 0:v)
+    MIDDLEOPTIONS+=(-c:v copy)
+    MIDDLEOPTIONS+=(-map 0:a)
+    MIDDLEOPTIONS+=(-c:a pcm_s24be)
+    MIDDLEOPTIONS+=(-ar 48000)
+    MIDDLEOPTIONS+=(-ac 2)
     
-    if [ "${codec_tag_string}" = "mpeg" ] ; then
-        extension="mxf"
+    if [ "${CODEC_TAG_STRING}" = "mpeg" ] ; then
+        EXTENSION="mxf"
     else
-        extension="mov"
+        EXTENSION="mov"
     fi
 
-    output_movie="${sourcefile%.*}${suffix}.${extension}"
-    if [ -f "${output_movie}" ] ; then
-        report -wt "The intended output of $(basename "${0}") already exists. Skipping for now. Please delete ${output_movie} and rerun or figure out why you are trying to do this."
+    OUTPUT_MOVIE="${SOURCEFILE%.*}${SUFFIX}.${EXTENSION}"
+    if [ -f "${OUTPUT_MOVIE}" ] ; then
+        _report -wt "The intended output of $(basename "${0}") already exists. Skipping for now. Please delete ${OUTPUT_MOVIE} and rerun or figure out why you are trying to do this."
     else
-        get_volume_adjustment "${sourcefile}"
+        _get_volume_adjustment "${SOURCEFILE}"
         if [ "${VOLADJ}" ] ; then
-            if [ $(echo "$VOLADJ < 2" |bc) -eq 1 -a $(echo "$VOLADJ > -2" |bc) -eq 1 ] ; then
-                report -dt "Integrated loudness for $(basename "${input_movie}") is ${integrated_loudness}dB. Reference is ${reference}dB. No adjustment is needed, skipping."
+            if [ $(echo "${VOLADJ} < 2" |bc) -eq 1 -a $(echo "${VOLADJ} > -2" |bc) -eq 1 ] ; then
+                _report -dt "Integrated loudness for $(basename "${INPUT_MOVIE}") is ${INTEGRATED_LOUDNESS}dB. Reference is ${REFERENCE}dB. No adjustment is needed, skipping."
             else
-                report -dt "Integrated loudness for $(basename "${input_movie}") is ${integrated_loudness}dB. Reference is ${reference}dB. Will adjust by ${VOLADJ}dB."
-                middleoptions+=(-af volume=${VOLADJ}dB)
-                report -dt "Generating ${output_movie} ... using these options: ${middleoptions[*]}"
-                ffmpeg -report -i "${sourcefile}" "${middleoptions[@]}" "${output_movie}"
-                report -dst "Done with ${name}."
+                _report -dt "Integrated loudness for $(basename "${INPUT_MOVIE}") is ${INTEGRATED_LOUDNESS}dB. Reference is ${REFERENCE}dB. Will adjust by ${VOLADJ}dB."
+                MIDDLEOPTIONS+=(-af volume=${VOLADJ}dB)
+                _report -dt "Generating ${OUTPUT_MOVIE} ... using these options: ${MIDDLEOPTIONS[*]}"
+                ffmpeg -report -i "${SOURCEFILE}" "${MIDDLEOPTIONS[@]}" "${OUTPUT_MOVIE}"
+                _report -dst "Done with ${NAME}."
             fi
         fi
     fi
diff --git a/makebroadcast b/makebroadcast
--- a/makebroadcast
+++ b/makebroadcast
@@ -4,21 +4,21 @@
 # v 1.2 revert to mov and ffmbc
 # v 1.3 revert back to ffmpeg
 # v 1.4 adjust handling volume adjustment argument
-version="1.4"
+VERSION="1.4"
 VOLADJUST="Y"
-scriptdir=$(dirname $(which "${0}"))
-. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
-dependencies=(ffmpeg ffprobe)
+SCRIPTDIR=$(dirname $(which "${0}"))
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
+DEPENDENCIES=(ffmpeg ffprobe)
 _initialize_make
-suffix=""
-extension="mov"
-relativepath="service"
+SUFFIX=""
+EXTENSION="mov"
+RELATIVEPATH="service"
 
 _usage(){
     echo
-    echo "$(basename "${0}") ${version}"
+    echo "$(basename "${0}") ${VERSION}"
     echo "This application will create a file suitable for broadcast or editing from a video file or package input with the following options."
-    echo "Dependencies: ${dependencies[@]}"
+    echo "Dependencies: ${DEPENDENCIES[@]}"
     echo "Usage: $(basename "${0}") [ -l ] [ -r ] [ -c ] fileorpackage1 [ fileorpackage2 ...]"
     echo "  -F (apply a formula, override default settings)"
     echo "  -l (only use the left channel of the first audio track)"
@@ -38,205 +38,205 @@ _usage(){
 
 # command-line options to set mediaid and original variables
 OPTIND=1
-while getopts ":F:lrcv:o:d:e:E:nh" opt ; do
-    case "${opt}" in
-        F) formula="${OPTARG}";;
-        l) audiomap="L";;
-        r) audiomap="R";;
-        c) cropdetect="Y" ;;
+while getopts ":F:lrcv:o:d:e:E:nh" OPT ; do
+    case "${OPT}" in
+        F) FORMULA="${OPTARG}";;
+        l) AUDIOMAP="L";;
+        r) AUDIOMAP="R";;
+        c) CROPDETECT="Y" ;;
         v) VOLADJUST="${OPTARG}";;
-        o) outputdir_forced="$OPTARG" && _check_outputdir_forced ;;
-        d) deliverdir="$OPTARG" && check_deliverdir ;;
-        e) emailaddress_delivery="$OPTARG" && check_emailaddress "${emailaddress_delivery}" ;;
-        E) emailaddress_outcome="$OPTARG" && check_emailaddress "${emailaddress_outcome}" ;;
+        o) OUTPUTDIR_FORCED="${OPTARG}" && _check_outputdir_forced ;;
+        d) DELIVERDIR="${OPTARG}" && _check_deliverdir ;;
+        e) EMAILADDRESS_DELIVERY="${OPTARG}" && check_emailaddress "${EMAILADDRESS_DELIVERY}" ;;
+        E) EMAILADDRESS_OUTCOME="${OPTARG}" && check_emailaddress "${EMAILADDRESS_OUTCOME}" ;;
         n) DRYRUN=true;;
         h) _usage ;;
-        *) echo "bad option -$OPTARG" ; _usage ;;
-        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
+        *) echo "bad option -${OPTARG}" ; _usage ;;
+        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="${1}"
+    INPUT="${1}"
     shift
-    if [ -z "${outputdir_forced}" ] ; then
-        [ -d "${input}" ] && { outputdir="${input}/objects/${relativepath}" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
-        [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/${relativepath}" && logdir="$(dirname "${input}")/${relativepath}/logs" ;};
-        [ ! "${outputdir}" ] && { outputdir="${input}/objects/${relativepath}" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
+    if [ -z "${OUTPUTDIR_FORCED}" ] ; then
+        [ -d "${INPUT}" ] && { OUTPUTDIR="${INPUT}/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/submissionDocumentation/logs" ;};
+        [ -f "${INPUT}" ] && { OUTPUTDIR=$(dirname "${INPUT}")"/${RELATIVEPATH}" && LOGDIR="$(dirname "${INPUT}")/${RELATIVEPATH}/logs" ;};
+        [ ! "${OUTPUTDIR}" ] && { OUTPUTDIR="${INPUT}/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/submissionDocumentation/logs" ;};
     else
-        outputdir="${outputdir_forced}"
-        logdir="${outputdir}/logs"
+        OUTPUTDIR="${OUTPUTDIR_FORCED}"
+        LOGDIR="${OUTPUTDIR}/logs"
     fi
-    _find_input "${input}"
-    mediaid=$(basename "${input}" | cut -d. -f1)
-    ingestlog="${logdir}/capture.log"
+    _find_input "${INPUT}"
+    MEDIAID=$(basename "${INPUT}" | cut -d. -f1)
+    INGESTLOG="${LOGDIR}/capture.log"
 
     _set_up_output
 
     # clear local arrays
-    intime=""
-    outtime=""
+    INTIME=""
+    OUTTIME=""
     audio_adjustment=""
-    unset inputoptions
-    unset middleoptions
-    unset middleoptionsxdcam
-    unset middleoptionsimx
-    unset audiomapping_ffmpeg
-    filterchain_start=""
-    get_videostreamcount "${sourcefile}"
-    get_audiostreamcount "${sourcefile}"
+    unset INPUTOPTIONS
+    unset MIDDLEOPTIONS
+    unset MIDDLEOPTIONSXDCAM
+    unset MIDDLEOPTIONSIMX
+    unset AUDIOMAPPING_FFMPEG
+    FILTERCHAIN_START=""
+    _get_videostreamcount "${SOURCEFILE}"
+    _get_audiostreamcount "${SOURCEFILE}"
 
 
     if [[ "${VIDEOSTREAMCOUNT}" > 0 ]] ; then
         # get information on the input
-        get_sar "${sourcefile}"
-        if [ "${cropdetect}" = "Y" ] ; then
-            get_cropdetection "${sourcefile}"
-            filterchain_start="${filterchain_start}${CROPADJ},"
-            width=$(echo "${CROPADJ}" | cut -d= -f2 | cut -d: -f1)
-            height=$(echo "${CROPADJ}" | cut -d= -f2 | cut -d: -f2)
-            dar="(${width}/${height})*${sar}"
+        _get_sar "${SOURCEFILE}"
+        if [ "${CROPDETECT}" = "Y" ] ; then
+            _get_cropdetection "${SOURCEFILE}"
+            FILTERCHAIN_START="${FILTERCHAIN_START}${CROPADJ},"
+            WIDTH=$(echo "${CROPADJ}" | cut -d= -f2 | cut -d: -f1)
+            HEIGHT=$(echo "${CROPADJ}" | cut -d= -f2 | cut -d: -f2)
+            DAR="(${WIDTH}/${HEIGHT})*${SAR}"
         else
-            get_width "${sourcefile}"
-            get_height "${sourcefile}"
-            get_dar "${sourcefile}"
+            _get_width "${SOURCEFILE}"
+            _get_height "${SOURCEFILE}"
+            _get_dar "${SOURCEFILE}"
         fi
 
         # set in and out times if used
-        if [[ -f "${ingestlog}" && "${isobject}" = "Y" ]] ; then
-            if [ ! ${formula} ] ; then
-                formula=$(_readingestlog "formula")
+        if [[ -f "${INGESTLOG}" && "${ISOBJECT}" = "Y" ]] ; then
+            if [ ! "${FORMULA}" ] ; then
+                FORMULA=$(_readingestlog "FORMULA")
             fi
-            intime=$(_readingestlog "intime")
-            outtime=$(_readingestlog "outtime")
-            if [[ "${intime}" ]] ; then
-                report -dt "ATTENTION: Transcoding will use intime (${intime}) during transcoding."
-                inputoptions+=(-seek_timestamp 1)
-                middleoptions+=(-ss "${intime}")
+            INTIME=$(_readingestlog "intime")
+            OUTTIME=$(_readingestlog "outtime")
+            if [[ "${INTIME}" ]] ; then
+                _report -dt "ATTENTION: Transcoding will use intime (${INTIME}) during transcoding."
+                INPUTOPTIONS+=(-seek_timestamp 1)
+                MIDDLEOPTIONS+=(-ss "${INTIME}")
             fi
-            if [[ "${outtime}" ]] ; then
-                report -dt "ATTENTION: Transcoding will use outtime (${outtime}) during transcoding."
-                middleoptions+=(-to "${outtime}")
+            if [[ "${OUTTIME}" ]] ; then
+                _report -dt "ATTENTION: Transcoding will use outtime (${OUTTIME}) during transcoding."
+                MIDDLEOPTIONS+=(-to "${OUTTIME}")
             fi
         fi
 
         #options for either xdcam or imx
-        middleoptions+=(-r ntsc)
-        middleoptions+=(-c:v mpeg2video)
-        middleoptions+=(-intra_vlc 1)
-        middleoptions+=(-non_linear_quant 1)
-        middleoptions+=(-qmin 1)
-        middleoptions+=(-dc 10)
-        middleoptions+=(-lmin QP2LAMBDA)
-        middleoptions+=(-ps 1)
-        middleoptions+=(-flags +ildct+ilme)
-        middleoptions+=(-pix_fmt yuv422p)
-        middleoptions+=(-metadata:s:v:0 timecode=00:00:00.00)
+        MIDDLEOPTIONS+=(-r ntsc)
+        MIDDLEOPTIONS+=(-c:v mpeg2video)
+        MIDDLEOPTIONS+=(-intra_vlc 1)
+        MIDDLEOPTIONS+=(-non_linear_quant 1)
+        MIDDLEOPTIONS+=(-qmin 1)
+        MIDDLEOPTIONS+=(-dc 10)
+        MIDDLEOPTIONS+=(-lmin QP2LAMBDA)
+        MIDDLEOPTIONS+=(-ps 1)
+        MIDDLEOPTIONS+=(-flags +ildct+ilme)
+        MIDDLEOPTIONS+=(-pix_fmt yuv422p)
+        MIDDLEOPTIONS+=(-metadata:s:v:0 timecode=00:00:00.00)
 
         #xdcam options
-        middleoptionsxdcam+=(-s 1920x1080)
-        middleoptionsxdcam+=(-vtag xd5b)
-        middleoptionsxdcam+=(-aspect 16:9)
-        middleoptionsxdcam+=(-q:v 1)
-        middleoptionsxdcam+=(-qmax 8)
-        middleoptionsxdcam+=(-g 15)
-        middleoptionsxdcam+=(-bf 2)
-        middleoptionsxdcam+=(-b:v 50M)
-        middleoptionsxdcam+=(-maxrate:v 50M)
-        middleoptionsxdcam+=(-minrate:v 50M)
-        middleoptionsxdcam+=(-bufsize 17825792)
-        middleoptionsxdcam+=(-rc_init_occupancy 17825792)
+        MIDDLEOPTIONSXDCAM+=(-s 1920x1080)
+        MIDDLEOPTIONSXDCAM+=(-vtag xd5b)
+        MIDDLEOPTIONSXDCAM+=(-aspect 16:9)
+        MIDDLEOPTIONSXDCAM+=(-q:v 1)
+        MIDDLEOPTIONSXDCAM+=(-qmax 8)
+        MIDDLEOPTIONSXDCAM+=(-g 15)
+        MIDDLEOPTIONSXDCAM+=(-bf 2)
+        MIDDLEOPTIONSXDCAM+=(-b:v 50M)
+        MIDDLEOPTIONSXDCAM+=(-maxrate:v 50M)
+        MIDDLEOPTIONSXDCAM+=(-minrate:v 50M)
+        MIDDLEOPTIONSXDCAM+=(-bufsize 17825792)
+        MIDDLEOPTIONSXDCAM+=(-rc_init_occupancy 17825792)
 
         # imx options
-        middleoptionsimx+=(-aspect 4:3)
-        middleoptionsimx+=(-qmax 12)
-        middleoptionsimx+=(-g 1)
-        middleoptionsimx+=(-top 1)
-        middleoptionsimx+=(-intra)
-        middleoptionsimx+=(-b:v 30M)
-        middleoptionsimx+=(-maxrate:v 30M)
-        middleoptionsimx+=(-minrate:v 30M)
-        middleoptionsimx+=(-bufsize 1001000)
-        middleoptionsimx+=(-rc_init_occupancy 1001000)
-        middleoptionsimx+=(-rc_max_vbv_use 1)
-        middleoptionsimx+=(-rc_min_vbv_use 1)
-        middleoptionsimx+=(-rc_buf_aggressivity 0.25)
-        middleoptionsimx+=(-vbsf imxdump)
-        middleoptionsimx+=(-tag:v mx3n)
+        MIDDLEOPTIONSIMX+=(-aspect 4:3)
+        MIDDLEOPTIONSIMX+=(-qmax 12)
+        MIDDLEOPTIONSIMX+=(-g 1)
+        MIDDLEOPTIONSIMX+=(-top 1)
+        MIDDLEOPTIONSIMX+=(-intra)
+        MIDDLEOPTIONSIMX+=(-b:v 30M)
+        MIDDLEOPTIONSIMX+=(-maxrate:v 30M)
+        MIDDLEOPTIONSIMX+=(-minrate:v 30M)
+        MIDDLEOPTIONSIMX+=(-bufsize 1001000)
+        MIDDLEOPTIONSIMX+=(-rc_init_occupancy 1001000)
+        MIDDLEOPTIONSIMX+=(-rc_max_vbv_use 1)
+        MIDDLEOPTIONSIMX+=(-rc_min_vbv_use 1)
+        MIDDLEOPTIONSIMX+=(-rc_buf_aggressivity 0.25)
+        MIDDLEOPTIONSIMX+=(-vbsf imxdump)
+        MIDDLEOPTIONSIMX+=(-tag:v mx3n)
 
         # decide on an output codec, aspect ratio, and padding strategy
-        darratio=$(echo "scale=3 ; ${dar}" | bc)
-        if [ "${formula}" = "tff" ] ; then
-            filterchain_start="${filterchain_start}setfield=tff,"
-        elif [ "${formula}" = "bff" ] ; then
-            filterchain_start="${filterchain_start}setfield=bff,"
+        DARRATIO=$(echo "scale=3 ; ${DAR}" | bc)
+        if [ "${FORMULA}" = "tff" ] ; then
+            FILTERCHAIN_START="${FILTERCHAIN_START}setfield=tff,"
+        elif [ "${FORMULA}" = "bff" ] ; then
+            FILTERCHAIN_START="${FILTERCHAIN_START}setfield=bff,"
         fi
-        get_fieldorder "${sourcefile}"
-        if [ "${fieldorder}" != "tff" ] ; then
-            filterchain_start="${filterchain_start}fieldorder=tff,"
+        _get_fieldorder "${SOURCEFILE}"
+        if [ "${FIELDORDER}" != "tff" ] ; then
+            FILTERCHAIN_START="${FILTERCHAIN_START}FIELDORDER=tff,"
         fi
-        if [ "${formula}" = "hds" ] ; then
-            middleoptions+=(-vf "${filterchain_start}scale=size=hd1080:interl=1,format=yuv422p,setsar=1/1,setdar=16/9,fps=fps=ntsc")
-            middleoptions+=(${middleoptionsxdcam[@]})
-        elif [ "${darratio}" = "1.777" -a ! "${cropdetect}" = "Y" ] ; then
-            middleoptions+=(-vf "${filterchain_start}scale=size=hd1080:interl=1,format=yuv422p,setsar=1/1,setdar=16/9,fps=fps=ntsc")
-            middleoptions+=(${middleoptionsxdcam[@]})
-        elif [ $(echo "scale=3 ; ${darratio} > (16/9)" | bc -l) = 1 ] ; then
-            middleoptions+=(-vf "${filterchain_start}pad=${width}:${width}*(9/16)*(${sar}):(ow-${width})/2:(oh-${height})/2,scale=size=hd1080:interl=1")
-            middleoptions+=(${middleoptionsxdcam[@]})
-        elif [ $(echo "scale=3 ; $darratio > (3/2)" | bc -l) = 1 ] ; then
-            middleoptions+=(-vf "${filterchain_start}pad=${height}*(16/9)/(${sar}):${height}:(ow-${width})/2:(oh-${height})/2,scale=size=hd1080:interl=1")
-            middleoptions+=(${middleoptionsxdcam[@]})
-        elif [ "$width" = "720" -a "$height" = "480" -a $(echo "scale=3 ; $darratio < (3/2)" | bc -l) = 1 -a ! "$cropdetect" = "Y" ] ; then
-            middleoptions+=(-vf ${filterchain_start}pad=720:512:0:24,setsar=1/1,setdar=4/3)
-            middleoptions+=(${middleoptionsimx[@]})
-        elif [ "${height}" -eq "486" -a "${width}" -eq "720" ] ; then
-            middleoptions+=(-vf "${filterchain_start}crop=720:480:0:4,pad=720:512:0:24,setsar=1/1,setdar=4/3")
-            middleoptions+=(${middleoptionsimx[@]})
-        elif  [ "${height}" -eq "512" -a "${width}" -eq "720" ] ;then
-            middleoptions+=(-vf "${filterchain_start}crop=720:480:0:32,pad=720:512:0:24,setsar=1/1,setdar=4/3")
-            middleoptions+=(${middleoptionsimx[@]})
+        if [ "${FORMULA}" = "hds" ] ; then
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}scale=size=hd1080:interl=1,format=yuv422p,setsar=1/1,setdar=16/9,fps=fps=ntsc")
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSXDCAM[@]}")
+        elif [ "${DARRATIO}" = "1.777" -a ! "${CROPDETECT}" = "Y" ] ; then
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}scale=size=hd1080:interl=1,format=yuv422p,setsar=1/1,setdar=16/9,fps=fps=ntsc")
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSXDCAM[@]}")
+        elif [ $(echo "scale=3 ; ${DARRATIO} > (16/9)" | bc -l) = 1 ] ; then
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}pad=${WIDTH}:${WIDTH}*(9/16)*(${SAR}):(ow-${WIDTH})/2:(oh-${HEIGHT})/2,scale=size=hd1080:interl=1")
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSXDCAM[@]}")
+        elif [ $(echo "scale=3 ; $DARRATIO > (3/2)" | bc -l) = 1 ] ; then
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}pad=${HEIGHT}*(16/9)/(${SAR}):${HEIGHT}:(ow-${WIDTH})/2:(oh-${HEIGHT})/2,scale=size=hd1080:interl=1")
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSXDCAM[@]}")
+        elif [ "${WIDTH}" = "720" -a "${HEIGHT}" = "480" -a $(echo "scale=3 ; ${DARRATIO} < (3/2)" | bc -l) = 1 -a ! "${CROPDETECT}" = "Y" ] ; then
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}"pad=720:512:0:24,setsar=1/1,setdar=4/3)
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSIMX[@]}")
+        elif [ "${HEIGHT}" -eq "486" -a "${WIDTH}" -eq "720" ] ; then
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}crop=720:480:0:4,pad=720:512:0:24,setsar=1/1,setdar=4/3")
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSIMX[@]}")
+        elif  [ "${HEIGHT}" -eq "512" -a "${WIDTH}" -eq "720" ] ;then
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}crop=720:480:0:32,pad=720:512:0:24,setsar=1/1,setdar=4/3")
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSIMX[@]}")
         else
-            middleoptions+=(-vf "${filterchain_start}scale=720:480,pad=720:512:0:24,setsar=1/1,setdar=4/3")
-            middleoptions+=(${middleoptionsimx[@]})
+            MIDDLEOPTIONS+=(-vf "${FILTERCHAIN_START}scale=720:480,pad=720:512:0:24,setsar=1/1,setdar=4/3")
+            MIDDLEOPTIONS+=("${MIDDLEOPTIONSIMX[@]}")
         fi
     fi
 
     if [[ "${AUDIOSTREAMCOUNT}" > 0 ]] ; then
-        get_audio_index "${sourcefile}"
-        if [ "${audiomap}" = "L" ] ; then
-            audiomapping_ffmpeg=(-map_channel 0.${audio_index_1}.0)
-        elif [ "${audiomap}" = "R" ] ; then
-            audiomapping_ffmpeg=(-map_channel 0.${audio_index_1}.1)
+        _get_audio_index "${SOURCEFILE}"
+        if [ "${AUDIOMAP}" = "L" ] ; then
+            AUDIOMAPPING_FFMPEG=(-map_channel 0.${AUDIO_INDEX_1}.0)
+        elif [ "${AUDIOMAP}" = "R" ] ; then
+            AUDIOMAPPING_FFMPEG=(-map_channel 0.${AUDIO_INDEX_1}.1)
         else
-            get_audio_mapping "${sourcefile}"
+            _get_audio_mapping "${SOURCEFILE}"
         fi
-        middleoptions+=(${audiomapping_ffmpeg[@]})
+        MIDDLEOPTIONS+=("${AUDIOMAPPING_FFMPEG[@]}")
         # add audio options
-        middleoptions+=(-acodec pcm_s24be)
-        middleoptions+=(-ar 48k)
-        middleoptions+=(-ac 2)
+        MIDDLEOPTIONS+=(-acodec pcm_s24be)
+        MIDDLEOPTIONS+=(-ar 48k)
+        MIDDLEOPTIONS+=(-ac 2)
     fi
 
     # set input options for ffmpeg
-    get_codectagstring "${sourcefile}"
-    inputoptions+=(-y)
-    inputoptions+=(-nostdin)
-    if [[ "${codec_tag_string}" == "mjp2" ]] ; then
-         inputoptions+=(-vcodec libopenjpeg)
+    _get_codectagstring "${SOURCEFILE}"
+    INPUTOPTIONS+=(-y)
+    INPUTOPTIONS+=(-nostdin)
+    if [[ "${CODEC_TAG_STRING}" == "mjp2" ]] ; then
+         INPUTOPTIONS+=(-vcodec libopenjpeg)
     fi
 
     # log process
     _prep_ffmpeg_log
     _prep_volume_adjustment
-    if [ "${concatsource}" != "" ] ; then
-        ffmpeginput="${concatsource}"
+    if [ "${CONCATSOURCE}" != "" ] ; then
+        FFMPEGINPUT="${CONCATSOURCE}"
     else
-        ffmpeginput="${sourcefile}"
+        FFMPEGINPUT="${SOURCEFILE}"
     fi
-    _run_critical ffmpeg ${inputoptions[@]} -i "${ffmpeginput}" ${middleoptions[@]} "${output}"
+    _run_critical ffmpeg "${INPUTOPTIONS[@]}" -i "${FFMPEGINPUT}" "${MIDDLEOPTIONS[@]}" "${OUTPUT}"
     echo
     _summarize_make
     _deliver_output "${MAKEBROADCAST_DELIVERY_EMAIL_TO}"
diff --git a/makemp3 b/makemp3
--- a/makemp3
+++ b/makemp3
@@ -1,93 +1,93 @@
 #!/bin/bash
 # makemp3
-version="1.0"
-unset dependencies
-dependencies=(ffmpeg normalize)
-suffix=""
-extension="mp3"
-relativepath="access/mp3"
+VERSION="1.0"
+unset DEPENDENCIES
+DEPENDENCIES=(ffmpeg normalize)
+SUFFIX=""
+EXTENSION="mp3"
+RELATIVEPATH="access/mp3"
 
-scriptdir=$(dirname "${0}")
-. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
+SCRIPTDIR=$(dirname "${0}")
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
 
-usage(){
+_usage(){
     echo
-    echo "$(basename "${0}") ${version}"
-    echo "This application will create an mp3 file from a video file or package input with the following options. By default the output will be written to ${outputdir}. You can override this with the -o option."
-    echo "Dependencies: ${dependencies[@]}"
+    echo "$(basename "${0}") ${VERSION}"
+    echo "This application will create an mp3 file from a video file or package input with the following options. By default the output will be written to ${OUTPUTDIR}. You can override this with the -o option."
+    echo "Dependencies: ${DEPENDENCIES[@]}"
     echo "Usage: $(basename "${0}") [ -o /directory/to/write/to/ ] fileorpackage1 [ fileorpackage2 ...]"
     echo "  -o directory ( directory to write the resulting file to )"
     echo "  -h ( display this help )"
     echo
     exit
 }
-[ "${#}" = 0 ] && usage
-check_dependencies "${dependencies[@]}"
+[ "${#}" = 0 ] && _usage
+_check_dependencies "${DEPENDENCIES[@]}"
 
-cleanup(){
+_cleanup(){
     _log -a "Process aborted"
     exit 1
 }
 
-trap cleanup SIGHUP SIGINT SIGTERM
+trap _cleanup SIGHUP SIGINT SIGTERM
 
 OPTIND=1
-while getopts ":ho:" opt; do
-    case "${opt}" in
-        h) usage ;;
-        o)             outputdir="${OPTARG}"
-            if [ ! -d "${outputdir}" ] ; then
-                report -wt "The output directory option, ${outputdir}, does not refer to an actual directory. Quitting."
+while getopts ":ho:" OPT; do
+    case "${OPT}" in
+        h) _usage ;;
+        o)             OUTPUTDIR="${OPTARG}"
+            if [ ! -d "${OUTPUTDIR}" ] ; then
+                _report -wt "The output directory option, ${OUTPUTDIR}, does not refer to an actual directory. Quitting."
                 exit 1
             fi
             ;;
-        *) echo "bad option -${OPTARG}" ; usage ;;
+        *) echo "bad option -${OPTARG}" ; _usage ;;
         :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
-    input="${1}"
-    if [ -z "${outputdir}" ] ; then
-        [ -d "${input}" ] && { outputdir="${input}/objects/${relativepath}" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
-        [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/${relativepath}" && logdir="$(dirname "${input}")/${relativepath}/logs" ;};
-        [ ! "${outputdir}" ] && { outputdir="${input}/objects/${relativepath}" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
+    INPUT="${1}"
+    if [ -z "${OUTPUTDIR}" ] ; then
+        [ -d "${INPUT}" ] && { OUTPUTDIR="${INPUT}/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/submissionDocumentation/logs" ;};
+        [ -f "${INPUT}" ] && { OUTPUTDIR=$(dirname "${INPUT}")"/${RELATIVEPATH}" && LOGDIR="$(dirname "${INPUT}")/${RELATIVEPATH}/logs" ;};
+        [ ! "${OUTPUTDIR}" ] && { OUTPUTDIR="${INPUT}/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/submissionDocumentation/logs" ;};
     else
-        logdir="${outputdir}/logs"
+        LOGDIR="${OUTPUTDIR}/logs"
     fi
 
-    _find_input "${input}"
+    _find_input "${INPUT}"
 
-    filename=$(basename "${sourcefile}")
-    mediaid=$(basename "${input}" | cut -d. -f1)
+    FILENAME=$(basename "${SOURCEFILE}")
+    MEDIAID=$(basename "${INPUT}" | cut -d. -f1)
 
     _log -b
 
     _set_up_output
     
-    unset inputoptions
-    unset middleoptions
-    inputoptions+=(-nostdin)
-    middleoptions+=(-map 0:a:0)
-    middleoptions+=(-ac 2)
-    middleoptions+=(-r:a 44100)
-    middleoptions+=(-sample_fmt s16p)
-    get_audio_mapping "${sourcefile}"
-    middleoptions+=(${audiomapping_ffmpeg[@]})
+    unset INPUTOPTIONS
+    unset MIDDLEOPTIONS
+    INPUTOPTIONS+=(-nostdin)
+    MIDDLEOPTIONS+=(-map 0:a:0)
+    MIDDLEOPTIONS+=(-ac 2)
+    MIDDLEOPTIONS+=(-r:a 44100)
+    MIDDLEOPTIONS+=(-sample_fmt s16p)
+    _get_audio_mapping "${SOURCEFILE}"
+    MIDDLEOPTIONS+=("${AUDIOMAPPING_FFMPEG[@]}")
 
-    if [ "${logdir}" != "" ] ; then
-        mkdir -p "${logdir}"
-        export FFREPORT="file=${logdir}/%p_%t_$(basename "${0}")_${version}.txt"
-        inputoptions+=(-v warning -stats)
+    if [ "${LOGDIR}" != "" ] ; then
+        mkdir -p "${LOGDIR}"
+        export FFREPORT="file=${LOGDIR}/%p_%t_$(basename "${0}")_${VERSION}.txt"
+        INPUTOPTIONS+=(-v warning -stats)
     fi
-    report -dt "Working on $(basename "${output}")."
-    report -dt "Running: ffmpeg ${inputoptions[@]} -i \"${sourcefile}\" ${middleoptions[@]} \"${output}\""
-    ffmpeg ${inputoptions[@]} -i "${sourcefile}" ${middleoptions[@]} "${output}"
-    report -dt "Adjusting highest audio peak to full scale..."
-    normalize --peak -v "${output}"
+    _report -dt "Working on $(basename "${OUTPUT}")."
+    _report -dt "Running: ffmpeg ${INPUTOPTIONS[@]} -i \"${SOURCEFILE}\" ${MIDDLEOPTIONS[@]} \"${OUTPUT}\""
+    ffmpeg "${INPUTOPTIONS[@]}" -i "${SOURCEFILE}" "${MIDDLEOPTIONS[@]}" "${OUTPUT}"
+    _report -dt "Adjusting highest audio peak to full scale..."
+    normalize --peak -v "${OUTPUT}"
     echo
-    report -dt "$(basename ${output}) is done."
+    _report -dt "$(basename ${OUTPUT}) is done."
     shift
     _log -e
 done
diff --git a/makepodcast b/makepodcast
--- a/makepodcast
+++ b/makepodcast
@@ -1,20 +1,20 @@
 #!/bin/bash
 # makepodcast, makes a file appropriate for podcasting
-version="1.0"
-scriptdir=$(dirname $(which "${0}"))
-. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
-dependencies=(ffmpeg ffprobe)
+VERSION="1.0"
+SCRIPTDIR=$(dirname $(which "${0}"))
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
+DEPENDENCIES=(ffmpeg ffprobe)
 _initialize_make
-suffix="_podcast"
-extension="mov"
-relativepath="access/podcast"
+SUFFIX="_podcast"
+EXTENSION="mov"
+RELATIVEPATH="access/podcast"
 
-usage(){
+_usage(){
     echo
-    echo "$(basename "${0}") ${version}"
+    echo "$(basename "${0}") ${VERSION}"
     echo "This application will create a QuickTime file suitable for podcasting from a video file or package input with the following options."
-    echo "Dependencies: ${dependencies[@]}"
-    echo "Usage: $(basename $0) [ -d /path/to/deliver/to/ ] fileorpackage1 [ fileorpackage2 ...]"
+    echo "Dependencies: ${DEPENDENCIES[@]}"
+    echo "Usage: $(basename ${0}) [ -d /path/to/deliver/to/ ] fileorpackage1 [ fileorpackage2 ...]"
     echo "  -d directory ( directory to deliver the resulting file to )"
     echo "  -o directory ( directory to write the resulting file to )"
     echo "  -n (dry-run mode, show the commands that would be run but don't do anything)"
@@ -24,76 +24,76 @@ usage(){
     echo
     exit
 }
-[ "${#}" = 0 ] && usage
+[ "${#}" = 0 ] && _usage
 
 # command-line options to set mediaid and original variables
 OPTIND=1
-while getopts ":o:d:e:E:nh" opt ; do
-    case "${opt}" in
-        o) outputdir_forced="$OPTARG" && _check_outputdir_forced ;;
-        d) deliverdir="$OPTARG" && check_deliverdir ;;
-        e) emailaddress_delivery="$OPTARG" && check_emailaddress "${emailaddress_delivery}" ;;
-        E) emailaddress_outcome="$OPTARG" && check_emailaddress "${emailaddress_outcome}" ;;
+while getopts ":o:d:e:E:nh" OPT ; do
+    case "${OPT}" in
+        o) OUTPUTDIR_FORCED="${OPTARG}" && _check_outputdir_forced ;;
+        d) DELIVERDIR="${OPTARG}" && _check_deliverdir ;;
+        e) EMAILADDRESS_DELIVERY="${OPTARG}" && check_emailaddress "${EMAILADDRESS_DELIVERY}" ;;
+        E) EMAILADDRESS_OUTCOME="${OPTARG}" && check_emailaddress "${EMAILADDRESS_OUTCOME}" ;;
         n) DRYRUN=true;;
-        h) usage ;;
-        *) echo "bad option -$OPTARG" ; usage ;;
-        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
+        h) _usage ;;
+        *) echo "bad option -${OPTARG}" ; _usage ;;
+        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
 
 while [ "${*}" != "" ] ; do
     # get context about the input
-    input="${1}"
+    INPUT="${1}"
     shift
-    if [ -z "${outputdir_forced}" ] ; then
-        [ -d "${input}" ] && { outputdir="$input/objects/${relativepath}" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
-        [ -f "${input}" ] && { outputdir=$(dirname "${input}")"/${relativepath}" && logdir="$(dirname "${input}")/${relativepath}/logs" ;};
-        [ ! "${outputdir}" ] && { outputdir="${input}/objects/${relativepath}" && logdir="${input}/metadata/submissionDocumentation/logs" ;};
+    if [ -z "${OUTPUTDIR_FORCED}" ] ; then
+        [ -d "${INPUT}" ] && { OUTPUTDIR="$INPUT/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/submissionDocumentation/logs" ;};
+        [ -f "${INPUT}" ] && { OUTPUTDIR=$(dirname "${INPUT}")"/${RELATIVEPATH}" && LOGDIR="$(dirname "${INPUT}")/${RELATIVEPATH}/logs" ;};
+        [ ! "${OUTPUTDIR}" ] && { OUTPUTDIR="${INPUT}/objects/${RELATIVEPATH}" && LOGDIR="${INPUT}/metadata/submissionDocumentation/logs" ;};
     else
-        outputdir="${outputdir_forced}"
-        logdir="${outputdir}/logs"
+        OUTPUTDIR="${OUTPUTDIR_FORCED}"
+        LOGDIR="${OUTPUTDIR}/logs"
     fi
-    _find_input "${input}"
-    mediaid=$(basename "${input}" | cut -d. -f1)
+    _find_input "${INPUT}"
+    MEDIAID=$(basename "${INPUT}" | cut -d. -f1)
 
     _set_up_output
 
     # clear local arrays
-    unset inputoptions
-    unset middleoptions
+    unset INPUTOPTIONS
+    unset MIDDLEOPTIONS
 
     # encoding options
-    get_codectagstring "${sourcefile}"
-    get_videostreamcount "${sourcefile}"
-    get_audiostreamcount "${sourcefile}"
-    inputoptions+=(-nostdin)
+    _get_codectagstring "${SOURCEFILE}"
+    _get_videostreamcount "${SOURCEFILE}"
+    _get_audiostreamcount "${SOURCEFILE}"
+    INPUTOPTIONS+=(-nostdin)
     if [[ "${VIDEOSTREAMCOUNT}" > 0 ]] ; then
-        if [[ "${codec_tag_string}" == "mjp2" ]] ; then
-             inputoptions+=(-vcodec libopenjpeg)
+        if [[ "${CODEC_TAG_STRING}" == "mjp2" ]] ; then
+             INPUTOPTIONS+=(-vcodec libopenjpeg)
         fi
-        middleoptions+=(-movflags faststart)
-        middleoptions+=(-pix_fmt yuv420p)
-        middleoptions+=(-c:v libx264)
-        middleoptions+=(-b:v 1500k)
-        middleoptions+=(-maxrate:v 3000k)
-        middleoptions+=(-minrate:v 375k)
-        middleoptions+=(-bufsize:v 6000k)
-        middleoptions+=(-vf "yadif,scale=640:trunc(ow/dar/2)*2:interl=1")
+        MIDDLEOPTIONS+=(-movflags faststart)
+        MIDDLEOPTIONS+=(-pix_fmt yuv420p)
+        MIDDLEOPTIONS+=(-c:v libx264)
+        MIDDLEOPTIONS+=(-b:v 1500k)
+        MIDDLEOPTIONS+=(-maxrate:v 3000k)
+        MIDDLEOPTIONS+=(-minrate:v 375k)
+        MIDDLEOPTIONS+=(-bufsize:v 6000k)
+        MIDDLEOPTIONS+=(-vf "yadif,scale=640:trunc(ow/dar/2)*2:interl=1")
     fi
     if [[ "${AUDIOSTREAMCOUNT}" > 0 ]] ; then
-        middleoptions+=(-c:a aac -strict -2)
-        middleoptions+=(-b:a 96k)
-        get_audio_mapping "${sourcefile}"
-        middleoptions+=(${audiomapping_ffmpeg[@]})
+        MIDDLEOPTIONS+=(-c:a aac -strict -2)
+        MIDDLEOPTIONS+=(-b:a 96k)
+        _get_audio_mapping "${SOURCEFILE}"
+        MIDDLEOPTIONS+=("${AUDIOMAPPING_FFMPEG[@]}")
     fi
     _prep_ffmpeg_log
-    if [ "${concatsource}" != "" ] ; then
-        ffmpeginput="${concatsource}"
+    if [ "${CONCATSOURCE}" != "" ] ; then
+        FFMPEGINPUT="${CONCATSOURCE}"
     else
-        ffmpeginput="${sourcefile}"
+        FFMPEGINPUT="${SOURCEFILE}"
     fi
-    _run_critical ffmpeg ${inputoptions[@]} -i "${ffmpeginput}" ${middleoptions[@]} "${output}"
+    _run_critical ffmpeg "${INPUTOPTIONS[@]}" -i "${FFMPEGINPUT}" "${MIDDLEOPTIONS[@]}" "${OUTPUT}"
     echo
     _summarize_make
     _deliver_output "${MAKEYOUTUBE_DELIVERY_EMAIL_TO}"
diff --git a/mmupdate b/mmupdate
--- a/mmupdate
+++ b/mmupdate
@@ -2,16 +2,16 @@
 # mmupdate
 # This script is only intended for use with computers that are not connceted to the internet to access github but need to efficiently install updates of mediamicroservices. A local path is setup via mmconfig and running 'mmupdate' will copy relavent files from that declared directory, $LOCAL_MM_DIR, to /usr/local/bin.
 
-scriptdir=`dirname "${0}"`
-. "${scriptdir}/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
+SCRIPTDIR=`dirname "${0}"`
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
 
 [ -z "${LOCAL_MM_DIR}" ] && { echo "A local directory of mediamicoservice must be declared. Run mmconfig to set LOCAL_MM_DIR." ; exit 1 ;};
-[ ! -d "${LOCAL_MM_DIR}" ] && { echo "mmupdate is configured to use $LOCAL_MM_DIR, which is not available. Run mmconfig to set LOCAL_MM_DIR." ; exit 1 ;};
-for script in barcodeinterpret blackatends checksumpackage fix_left2stereo fix_rewrap fix_volume ingestfile ingestfile makebroadcast makedvd makeframes makelossless makemetadata makepodcast makeprores makeyoutube mmconfig mmfunctions mmhelp paperingest quickcompare removeDSStore uploadomneon xdcamingest mmupdate checksum2filemaker ; do
-    if [ -f "${LOCAL_MM_DIR}/${script}" ] ; then
-        rm "/usr/local/bin/${script}"
+[ ! -d "${LOCAL_MM_DIR}" ] && { echo "mmupdate is configured to use ${LOCAL_MM_DIR}, which is not available. Run mmconfig to set LOCAL_MM_DIR." ; exit 1 ;};
+for SCRIPT in barcodeinterpret blackatends checksumpackage fix_left2stereo fix_rewrap fix_volume ingestfile ingestfile makebroadcast makedvd makeframes makelossless makemetadata makepodcast makeprores makeyoutube mmconfig mmfunctions mmhelp paperingest quickcompare removeDSStore uploadomneon xdcamingest mmupdate checksum2filemaker ; do
+    if [ -f "${LOCAL_MM_DIR}/${SCRIPT}" ] ; then
+        rm "/usr/local/bin/${SCRIPT}"
     fi
-    cp -v -f -p "${LOCAL_MM_DIR}/${script}" /usr/local/bin/
+    cp -v -f -p "${LOCAL_MM_DIR}/${SCRIPT}" /usr/local/bin/
 done
 if [ -d "${LOCAL_MM_DIR}/extra_installs/" ] ; then
     cp -v -f -p "${LOCAL_MM_DIR}/extra_installs/"* /usr/local/bin/
