added _writeerrorlog functionality

diff --git a/checksumpackage b/checksumpackage
--- a/checksumpackage
+++ b/checksumpackage
@@ -32,6 +32,7 @@ _usage(){
 _check_dependencies "${DEPENDENCIES[@]}"
 if [[ $(echo "$(md5deep -v) >= 4.4" | bc) = 0 ]] ; then
     _report -wt "$(basename "${0}") requires md5deep 4.4 or greater."
+    _writeerrorlog "checksumpackage" "checksumpackage was unable to run because md5deep 4.4 or greater is required."
     exit 1
 fi
 _cleanup(){
@@ -51,7 +52,7 @@ while getopts ":cvuh" OPT ; do
        u) UPDATE="Y";;
        h) _usage ;;
        *) echo "bad option -${OPTARG}" ; _usage ;;
-       :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+       :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "checksumpackage" "You used an invalid option and the script had to exit" ; exit 1 ;;
    esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -131,6 +132,7 @@ while [ "${*}" != "" ] ; do
                 fi
             else
                 _report -dt "There is no dfxml.xml to check in ${PACKAGE}, skipping."
+                _writeerrorlog "checksumpackage" "There was no dfxml.xml to check in ${PACKAGE}, so it was skipped."
                 shift
                 continue
             fi
@@ -139,6 +141,7 @@ while [ "${*}" != "" ] ; do
                     _report -dt "Prepping for dfxml.xml verification."
                 else
                     _report -dt "There is no dfxml.xml to verify in ${PACKAGE}, skipping."
+                    _writeerrorlog "checksumpackage" "There was no dfxml.xml to verify in ${PACKAGE}, so it was skipped."
                     shift
                     continue
                 fi
diff --git a/fix_volume b/fix_volume
--- a/fix_volume
+++ b/fix_volume
@@ -29,8 +29,8 @@ OPTIND=1
 while getopts ":h" OPT ; do
     case "${OPT}" in
         h) _usage ;;
-        *) echo "Invalid option: -${OPTARG}" ; exit 1 ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        *) echo "Invalid option: -${OPTARG}" ; _writeerrorlog "fix_volume" "You used an invalid option and the script had to exit." ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "fix_volume" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
diff --git a/ingestfile b/ingestfile
--- a/ingestfile
+++ b/ingestfile
@@ -15,6 +15,7 @@ DELIVERYTOOMNEON="Y"       # use 'Y' for yes or any other character for no
 DELIVERACCESSCOPIES="Y"    # use 'Y' for yes or any other character for no
 DELIVERYTOAIPSTORAGE="Y"   # use 'Y' for yes or any other character for no
 
+
 QUEUEFILE="${HOME}/Desktop/queue.txt"
 SCRIPTDIR=$(dirname "${0}")
 . "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
@@ -43,20 +44,20 @@ while getopts ":F:pnhei" OPT ; do
         i) DELIVERYTOOMNEON="Y" ; DELIVERACCESSCOPIES="N" ; DELIVERYTOAIPSTORAGE="Y" ;;
         h) _usage ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ;  _writeerrorlog "ingestfile" "You used an invalid option and the script had to exit" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
 
 _add_mediaid_to_queue(){
-    [ -n "${MEDIAID}" ] || { _report -wt "Error: mediaid is undefined in add_media_to_queue function" ; exit 1 ;};
-    [ -n "${QUEUEFILE}" ] || { _report -wt "Error: queuefile is undefined in add_media_to_queue function" ; exit 1 ;};
+    [ -n "${MEDIAID}" ] || { _report -wt "Error: mediaid is undefined in add_media_to_queue function" ; _writeerrorlog "_add_mediaid_to_queue" "The media id is undefined in the _add_mediaid_to_queue function, and caused the script to exit." ; exit 1 ;};
+    [ -n "${QUEUEFILE}" ] || { _report -wt "Error: queuefile is undefined in add_media_to_queue function" ; _writeerrorlog "_add_mediaid_to_queue" "The queuefile is undefined in the _add_mediaid_to_queue function, and caused the script to exit." ; exit 1 ;};
     echo "${MEDIAID}" >> "${QUEUEFILE}"
 }
 
 _remove_mediaid_from_queue(){
-    [ -n "${MEDIAID}" ] || { _report -wt "Error: mediaid is undefined in remove_media_from_queue function" ; exit 1 ;};
-    [ -f "${QUEUEFILE}" ] || { _report -wt "Error: queuefile is undefined in remove_media_from_queue function" ; exit 1 ;};
+    [ -n "${MEDIAID}" ] || { _report -wt "Error: mediaid is undefined in remove_media_from_queue function" ; _writeerrorlog "_remove_mediaid_from_queue" "The media id is undefined in the _remove_mediaid_from_queue function, and caused the script to exit." ; exit 1 ;};
+    [ -f "${QUEUEFILE}" ] || { _report -wt "Error: queuefile is undefined in remove_media_from_queue function" ; _writeerrorlog "_remove_mediaid_from_queue" "The queuefile is undefined in the _remove_mediaid_from_queue function, and caused the script to exit." ; exit 1 ;};
     grep -v "^${MEDIAID}$" "${QUEUEFILE}" | grep "^[A-Z0-9_-]\+$" > "${QUEUEFILE}_tmp"
     rm "${QUEUEFILE}"
     mv "${QUEUEFILE}_tmp" "${QUEUEFILE}"
@@ -199,8 +200,14 @@ _ask_operator
 _ask_mediaid
 
 ## check for existing output
-[ -d "${OUTDIR_INGESTFILE}/${MEDIAID}" ] && { _report -wt "It looks like ${MEDIAID} was already ingested. If you want to overwrite the existing one please delete ${OUTDIR_INGESTFILE}/${MEDIAID} first and then try again." ; exit 1 ;};
-[ -d "${AIP_STORAGE}/${MEDIAID}" ] && { _report -wt "It looks like ${MEDIAID} was already ingested. If you want to overwrite the existing one please delete ${AIP_STORAGE}/${MEDIAID} first and then try again." ; exit 1 ;};
+if [ -d "${OUTDIR_INGESTFILE}/${MEDIAID}" ] ; then
+     _report -wt "It looks like ${MEDIAID} was already ingested. If you want to overwrite the existing one please delete ${OUTDIR_INGESTFILE}/${MEDIAID} first and then try again." 
+     exit 1 
+fi
+if [ -d "${AIP_STORAGE}/${MEDIAID}" ] ; then 
+    _report -wt "It looks like ${MEDIAID} was already ingested. If you want to overwrite the existing one please delete ${AIP_STORAGE}/${MEDIAID} first and then try again." 
+    exit 1
+fi
 _ask_input
 #here is where we would insert an option for searching for  directory. 
 if [ ! $(_is_video "${INPUT}") ] ; then
@@ -352,6 +359,7 @@ TO=$(_get_filesystem "${OBJECTSDIR}/")
 # make sure the input is still there
 if [ ! -f "${INPUT}" ] ; then
     _report -wt "The input file is no longer available! Where did $(basename "${INPUT}") go? Please redo."
+    _writeerrorlog "ingestfile" "The input file, $(basename "${INPUT}"), was no longer available, so ingest file could not continue."
     # clean up queue
     [ "${PRIORITY}" == "put in queue" ] && _cleanup
     exit 1
@@ -416,6 +424,7 @@ if [ "${MAKEACCESSCOPIES}" == "Y" ] ; then
         "${SCRIPTDIR}/makepodcast" "${MAKEPODCASTOPTS[@]}" "${OUTDIR_INGESTFILE}/${MEDIAID}"
     else
         _report -dt "${MEDIAID} does NOT qualify for podcast creation, skipping."
+        _writeerrorlog "makepodcast" "${MEDIAID} did not qualify for podcast creation and was skipped."
     fi
     # makedvd
     "${SCRIPTDIR}/makedvd" "${OUTDIR_INGESTFILE}/${MEDIAID}"
@@ -442,6 +451,7 @@ if [ "${DELIVERYTOAIPSTORAGE}" == "Y" ] ; then
     [ $(du -s "${OUTDIR_INGESTFILE}/${MEDIAID}" | awk '{print $1}') = "0" ] && rm -r "${OUTDIR_INGESTFILE}/${MEDIAID}"
     _report -dt "STATUS Done. Final package has been delivered to ${AIP_STORAGE}/${MEDIAID}"
 fi
+    
 if [ "${CLEANUP_CHOICE}" == "Y" ] ; then
     if [ "${RSYNC_ERR}" -gt "0" ] ; then
         _report -wt "Cancelling requested deletion of source file, not looking safe."
diff --git a/makelossless b/makelossless
--- a/makelossless
+++ b/makelossless
@@ -28,7 +28,7 @@ while getopts ":jnh" OPT ; do
         n) DRYRUN=true;;
         h) _usage ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makelossless" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -99,6 +99,7 @@ while [ "${*}" != "" ] ; do
             fi
         else
             _report -wt "${SOURCEFILENAME} is not 2vuy or v210 or progressive ffv1, skipping"
+            _writeerrorlog "makelossless" "The source file is not 2vuy or v210 or progressive ffv1, so makelossless was unable to run."
             continue
         fi
         _report -dt done with "${SOURCEFILE}"
diff --git a/makemetadata b/makemetadata
--- a/makemetadata
+++ b/makemetadata
@@ -22,7 +22,7 @@ while getopts ":h" OPT ; do
     case "${OPT}" in
         h) _usage ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makemetadata" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
diff --git a/makemp3 b/makemp3
--- a/makemp3
+++ b/makemp3
@@ -38,11 +38,12 @@ while getopts ":ho:" OPT; do
         o)             OUTPUTDIR="${OPTARG}"
             if [ ! -d "${OUTPUTDIR}" ] ; then
                 _report -wt "The output directory option, ${OUTPUTDIR}, does not refer to an actual directory. Quitting."
+                _writeerrorlog "makemp3" "The directory specified for the output does not refer to an actual directory, forcing the script to quit."
                 exit 1
             fi
             ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makemp3" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
diff --git a/makepdf b/makepdf
--- a/makepdf
+++ b/makepdf
@@ -63,7 +63,7 @@ while getopts ":o:d:e:E:nh" OPT ; do
         n) DRYRUN=true;;
         h) _usage ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makepdf" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -92,6 +92,7 @@ while [ "${*}" != "" ] ; do
         SOURCEDIR="${INPUT}/objects"
     else
         _report -wt "No source objects folder"
+        _writeerrorlog "makepdf" "No source objects folder provided. The script could not continue."
         exit 1
     fi
     MEDIAID=$(basename "${INPUT}" | cut -d. -f1)
diff --git a/makepodcast b/makepodcast
--- a/makepodcast
+++ b/makepodcast
@@ -37,7 +37,7 @@ while getopts ":o:d:e:E:nh" OPT ; do
         n) DRYRUN=true;;
         h) _usage ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makepodcast" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
diff --git a/makeyoutube b/makeyoutube
--- a/makeyoutube
+++ b/makeyoutube
@@ -45,7 +45,7 @@ while getopts ":lrv:o:d:e:E:nhY" OPT ; do
         Y) YOUTUBEUPLOAD="Y";;
         h) _usage ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makeyoutube" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -139,6 +139,7 @@ while [ "${*}" != "" ] ; do
             echo "$(_get_iso8601),${OUTPUT},attempted upload,$?" >> "${HOME}/Desktop/upload.log"
         else
             _report -wt "$(basename "${OUTPUT}") qualified for uploadyoutube but it is not installed."
+            _writeerrorlog "makeyoutube" "$(basename "${OUTPUT}") qualified for uploadyoutube but it is not installed, so the file could not be uploaded."
         fi
     fi
     _log -e
diff --git a/mmfunctions b/mmfunctions
--- a/mmfunctions
+++ b/mmfunctions
@@ -40,6 +40,18 @@ _mkdir2(){
     done
 }
 
+_writeerrorlog(){
+    if [ ! -d "${ERRORLOGS}" ] ; then
+        mkdir ~/Desktop/ERRORLOGS/
+        touch ~/Desktop/ERRORLOGS/error.log
+    fi
+        ERRORLOG=~/Desktop/ERRORLOGS/error.log
+        KEY="${1}"
+        VALUE="${2}"
+        DATE=$(_get_iso8601_c)
+        echo "${MEDIAID}, ${DATE}, ${KEY}: ${VALUE}" >> "${ERRORLOG}"
+}
+
 _log(){
     MMLOGNAME="mm.log"
     MMLOGDIR="${CUSTOM_LOG_DIR:-/tmp}"
@@ -123,6 +135,7 @@ _run(){
     RUN_ERR="${?}"
     if [[ "${RUN_ERR}" != 0 ]] ; then
     _report -wts "Error: Running: \"${*}\" gave an Error Code - ${RUN_ERR}"
+    _writeerrorlog "_run" "Running: \"${*}\" gave an Error Code - ${RUN_ERR}"
     fi
 }
 
@@ -149,6 +162,7 @@ _maketemp(){
     mktemp -q "/tmp/$(basename "${0}").XXXXXX"
     if [ "${?}" -ne 0 ]; then
         echo "${0}: Can't create temp file, exiting..."
+        _writeerrorlog "_maketemp" "was unable to create the temp file, so the script had to exit."
         exit 1
     fi
 }
@@ -275,12 +289,14 @@ _initialize_make(){
 _check_deliverdir(){
     if [ ! -d "${DELIVERDIR}" ] ; then
         _report -wt "The delivery directory, ${DELIVERDIR}, does not exist. Can not deliver the OUTPUT of $(basename "${0}")."
+        _writeerrorlog "_checkdeliverdir" "The specified delivery directory does not exist, and the output could not be delivered."
     fi
 }
 
 _check_outputdir_forced(){
     if [ ! -d "${OUTPUTDIR_FORCED}" ] ; then
         _report -wt "The directory, ${OUTPUTDIR_FORCED}, does not exist. Can not write the output of $(basename "${0}")."
+        _writeerrorlog "_check_outputdir_forced" "The specified directory does not exist, and the output could not be delivered."
     fi
 }
 
@@ -288,6 +304,7 @@ _check_emailaddress(){
     EMAILREGEX="^((\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)*([,])*)*$"
     if ! $(echo "${1}" | grep -Eq "^((\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*)*([,])*)*$") ; then
         _report -wt "${1} is not a valid email address."
+        _writeerrorlog "_check_emailaddress" "The email address provided was not a valid email address."
     fi
 }
 
@@ -404,7 +421,11 @@ _find_input (){
     [ -d "${1}" ] && [ -d "${1}/objects/service" ] && ISOBJECT="N" && SOURCEFILE=$(find "${1}/objects/service" -maxdepth 1 -mindepth 1 -type f \( -iname "*.mov" -o -iname "*.mxf" -o -iname "*.mp4" -o -iname "*.dv" -o -iname "*.mpeg" -o -iname "*.iso" -o -iname "*.mkv" -o -iname "*.m2ts" \) ! -name ".*" | head -n 1)
     [ -f "${1}" ] && SOURCEFILE="${1}"
     [ ! "${SOURCEFILE}" ] && [ -d "${1}/objects" ] && ISOBJECT="Y" && SOURCEFILE=$(find "${1}/objects" -maxdepth 1 -mindepth 1 -type f \( -iname "*.mov" -o -iname "*.mxf" -o -iname "*.mp4" -o -iname "*.dv" -o -iname "*.mpeg" -o -iname "*.iso" -o -iname "*.mkv" -o -iname "*.m2ts" \) ! -name ".*" | head -n 1)
-    [ ! "${SOURCEFILE}" ] && { _report -wt "A valid source file isn't found." ; exit 1 ;};
+    if [ ! "${SOURCEFILE}" ] ; then 
+        _report -wt "A valid source file isn't found."
+        _writeerrorlog "_find_input" "A valid source file was not found, so the script could not proceed." 
+        exit 1
+    fi 
     LOG+="SOURCEFILE: ${SOURCEFILE}\n"
     if [ "${SOURCEFILE#*.}" == "iso" ] ; then
         _report -dt "Detecting iso input and hoping its a dvd image"
@@ -427,6 +448,7 @@ _find_input (){
         _report -wt "Extracting to ${MOUNTPATH}. Please delete ${MOUNTPATH} later"
         if [ "${CONCATSOURCE}" == "" ] ; then
             _report -wt "ERROR: Can not mount iso or find vob files to concatenate within ${OLDSOURCEFILE}. Exiting."
+            _writeerrorlog "_find_input" "Could not mount iso or find vob files to concatenate within ${OLDSOURCEFILE}."
             exit
         fi
     fi
@@ -683,11 +705,15 @@ _free_space(){
     #this should give the free space in gigabytes
     local SPACE="${1}"  #This value represents the space in gigabytes required for the script to run
     local OUTPUTDIR="${2}"
-    [ ! -d "${OUTPUTDIR}" ] && { _report -wt "The output directory [${OUTPUTDIR}] that free-space function is seeking does not exist." ; exit 1 ;};
+    if [ ! -d "${OUTPUTDIR}" ] ; then
+        _report -wt "The output directory [${OUTPUTDIR}] that free-space function is seeking does not exist." 
+        exit 1
+    fi
     [[ ! "${SPACE}" =~ ^-?[0-9]+$ ]] && { _report -wt "Number is not an integer." ; exit 1 ;};
     FREESPACE=$(df -g "${OUTPUTDIR}" | awk '{ print $4; }' | tail -n 1)
-    if [ "${FREESPACE}" -lt "${SPACE}" ]; then
+    if [ "${FREESPACE}" -lt "${SPACE}" ] ; then
       _report -wts "ERROR only ${FREESPACE} gb free in this directory. This script requires at least ${SPACE} gigabytes"
+      _writeerrorlog "_free_space" "There is only ${FREESPACE} gb free in this directory. This script requires at least ${SPACE} gigabytes to run."
       exit 1
     fi
 }
