updates for usability in createpremisdb
Added error checking, option to continue to user creation after db
creation, enabled slashes in user input and cleaned up a bit

diff --git a/createpremisdb b/createpremisdb
--- a/createpremisdb
+++ b/createpremisdb
@@ -1,10 +1,18 @@
 #!/bin/bash
 
 usage(){
+    echo "This script will configure a database, users and login profiles"
     echo "Usage: -c (create database) -u (create user) -h (help)"
 }
 
-file_input=$1
+_error_check(){
+#verify success of operation
+if [ "$?" != "0" ]; then
+echo -e "\033[1;5;95mERROR:\033[0m \033[1;93mPlease confirm inputs and try again.\033[0m"
+mysql_config_editor remove --login-path=tempsetting
+exit 1
+fi
+}
 
 OPTIND=1
 while getopts "hcu" opt ; do
@@ -24,38 +32,57 @@ fi
 if [ "$runtype" = "create" ] ; then
 #get input for database creation
 echo "Please enter the location the database will be created"
-read DB_HOST
+read -r DB_HOST
 echo "Please enter root password for mysql:"
 mysql_config_editor set --login-path=tempsetting --host="$DB_HOST" --user=root --password
 echo "Please enter name of DB to be created"
-read DB_NAME
+read -r DB_NAME
+
 #create database
 echo "CREATE DATABASE "$DB_NAME"" | mysql --login-path=tempsetting
+_error_check
 echo "CREATE TABLE object (objectIdentifierValue varchar(1000) NOT NULL,contentLocationValue varchar (300),PRIMARY KEY (objectIdentifierValue))" | mysql --login-path=tempsetting "$DB_NAME"
 echo "CREATE TABLE event (eventIdentifierValue bigint NOT NULL AUTO_INCREMENT,objectIdentifierValue varchar(1000) NOT NULL,eventType varchar(100) NOT NULL,eventDateTime datetime NOT NULL DEFAULT NOW(),eventDetail varchar(30) NOT NULL,eventDetailOPT varchar(1000),eventDetailCOMPNAME varchar(50) NOT NULL,linkingAgentIdentifierValue varchar(30) NOT NULL,PRIMARY KEY (eventIdentifierValue),FOREIGN KEY (objectIdentifierValue) REFERENCES object(objectIdentifierValue))" | mysql --login-path=tempsetting "$DB_NAME"
 echo "CREATE TABLE fixity (fixityIdentifierValue bigint NOT NULL AUTO_INCREMENT,objectIdentifierValue varchar(1000),eventDateTime datetime NOT NULL DEFAULT NOW(),messageDigestAlgorithm varchar (20) NOT NULL,messageDigestPATH varchar (8000) NOT NULL,messageDigestFILENAME varchar (8000) NOT NULL,messageDigestHASH varchar (32) NOT NULL,PRIMARY KEY (fixityIdentifierValue),FOREIGN KEY (objectIdentifierValue) REFERENCES object(objectIdentifierValue))" | mysql --login-path=tempsetting "$DB_NAME"
+_error_check
 #remove root config
 mysql_config_editor remove --login-path=tempsetting
+
+#Option to continue on to user creation
+echo -e "\033[1;95mDatabase has been created\033[0m"
+echo -e "\033[1;93mDo You wish to create a user? Y or N?\033[0m"
+read user_input
+continue=$(echo "$user_input" | tr '[:upper:]' '[:lower:]')
+if [ "$continue" = "y" ] ; then
+    runtype="user"
+fi
 fi
 
 #create user option
 if [ "$runtype" = "user" ] ; then
 #get input for user creation
+if [ -z "$DB_NAME" ] ; then
 echo "Please enter the name of target database"
-read DB_NAME
+read -r DB_NAME
+fi
+if [ -z "$DB_HOST" ] ; then
 echo "Please enter the location of target database"
-read DB_HOST
+read -r DB_HOST
+fi
 echo "Please enter the name of user to be created"
-read USER_NAME
+read -r USER_NAME
 echo "Please enter the password for the new user"
-read USER_PASSWORD
+read -r USER_PASSWORD
 echo "Please enter the location of user to be created"
-read USER_HOST
+read -r USER_HOST
 echo "Please enter mysql root password"
 mysql_config_editor set --login-path=tempsetting --host="$DB_HOST" --user=root --password
+
 #create user
 echo "CREATE USER \""$USER_NAME"\"@\""$USER_HOST"\" IDENTIFIED BY \""$USER_PASSWORD"\"" | mysql --login-path=tempsetting
+_error_check
 echo "GRANT ALL PRIVILEGES ON "$DB_NAME".* TO \""$USER_NAME"\"@\""$USER_HOST"\"" | mysql --login-path=tempsetting
+_error_check
 echo "FLUSH PRIVILEGES" | mysql --login-path=tempsetting
 
 #set up and run expect script for creation of mysql login config
