fix_volume: bracketed variables

diff --git a/fix_volume b/fix_volume
--- a/fix_volume
+++ b/fix_volume
@@ -6,29 +6,29 @@ dependencies=(ffmbc ffmbc)
 # local variables
 suffix="_voladj"
 
-scriptdir=$(dirname "$0")
-. "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+scriptdir=$(dirname "${0}")
+. "$scriptdir/mmfunctions" || { echo "Missing '${scriptdir}/mmfunctions'. Exiting." ; exit 1 ;};
 
 usage(){
     echo
-    echo "$(basename $0) ${version}"
+    echo "$(basename ${0}) ${version}"
     echo "This application will use an input video file to produce an output video file where the audio is adjusted to meet an integrated loudness of -23dB. If the integrated loudness of the input is already within 1dB of the target then no change will occur. The output file will be produced in the same directory as the input but be distinguished by a suffix in the filename: ${suffix}."
     echo "Dependencies: ${dependencies[@]}"
-    echo "Usage: $(basename $0) file1 [ file2 ...]"
+    echo "Usage: $(basename ${0}) file1 [ file2 ...]"
     echo "  -h display this help"
     echo
     exit
 }
-[ "$#" = 0 ] && usage
+[ "${#}" = 0 ] && usage
 check_dependencies "${dependencies[@]}"
 
 # command line arguments
 OPTIND=1
 while getopts ":h" opt ; do
-    case $opt in
+    case ${opt} in
         h) usage ;;
-        *) echo "Invalid option: -$OPTARG" ; exit 1 ;;
-        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
+        *) echo "Invalid option: -${OPTARG}" ; exit 1 ;;
+        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -42,8 +42,8 @@ trap cleanup SIGHUP SIGINT SIGTERM
 log -b
 
 while [ "$*" != "" ] ; do
-    input_movie="$1"
-    name=$(basename "$1")
+    input_movie="${1}"
+    name=$(basename "${1}")
     extension="${name#*.}"
     
     get_codectagstring
@@ -55,7 +55,7 @@ while [ "$*" != "" ] ; do
 
     output_movie="${input_movie%.*}${suffix}.${extension}"
     if [ -f "${output_movie}" ] ; then
-        report -wt "The intended output of $(basename $0) already exists. Skipping for now. Please delete ${output_movie} and rerun or figure out why you are trying to do this."
+        report -wt "The intended output of $(basename ${0}) already exists. Skipping for now. Please delete ${output_movie} and rerun or figure out why you are trying to do this."
     else
         get_volume_adjustment "${input_movie}"
         if [ -n "${VOLADJ}" ] ; then
@@ -64,7 +64,7 @@ while [ "$*" != "" ] ; do
             ffmpeg -i ${input_movie} -af volume=${VOLADJ}dB ${audio_pipe_opts[@]} - | ffmbc -i ${input_movie} ${ffmbc_opts[@]} ${audio_pipe_opts[@]} -i pipe:0 -map 0:v -map 1:a -acodec pcm_s24be -ar 48000 -ac 2 ${output_movie}
             report -dst "Done with ${name}."
         else
-            report -dst "Integrated loudness for $name is ${integrated_loudness}dB. Reference is ${reference}. No adjustment is needed for ${name}, skipping."
+            report -dst "Integrated loudness for ${name} is ${integrated_loudness}dB. Reference is ${reference}. No adjustment is needed for ${name}, skipping."
         fi
     fi
     shift
