fix_left2stereo: add cleanup/trap and log functions

diff --git a/fix_left2stereo b/fix_left2stereo
--- a/fix_left2stereo
+++ b/fix_left2stereo
@@ -6,6 +6,14 @@ scriptdir=`dirname "$0"`
 . "$scriptdir/mmfunctions"
 [ ! -f "$scriptdir/mmvariables" -o ! -f "$scriptdir/mmfunctions" ] && { echo "Missing '$scriptdir/mmvariables' and/or '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
 
+cleanup(){
+	log -a "Process aborted"
+	exit 1
+}
+
+trap cleanup SIGHUP SIGINT SIGTERM
+log -b
+
 suffix="_left2stereo"
 
 if test $# != 1 ; then
@@ -32,3 +40,4 @@ while [ "$*" != "" ] ; do
 	fi
 	shift
 done
+log -e
