ingestfile: add cleanup/trap and log functions

diff --git a/ingestfile b/ingestfile
--- a/ingestfile
+++ b/ingestfile
@@ -14,6 +14,14 @@ scriptdir=`dirname "$0"`
 . "$scriptdir/mmfunctions"
 [ ! -f "$scriptdir/mmvariables" -o ! -f "$scriptdir/mmfunctions" ] && { echo "Missing '$scriptdir/mmvariables' and/or '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
 
+cleanup(){
+	log -a "Process aborted"
+	exit 1
+}
+
+trap cleanup SIGHUP SIGINT SIGTERM
+log -b
+
 usage(){
 	echo
 	echo "$(basename $0) ${version}"
@@ -212,3 +220,5 @@ if [ "$priority" == "put in queue" ] ; then
 	rm /tmp/queue.txt
 	mv /tmp/queue2.txt /tmp/queue.txt
 fi
+done
+log -e
