makedvd: add cleanup/trap and log functions

diff --git a/makedvd b/makedvd
--- a/makedvd
+++ b/makedvd
@@ -8,6 +8,14 @@ scriptdir=`dirname "$0"`
 . "$scriptdir/mmfunctions"
 [ ! -f "$scriptdir/mmvariables" -o ! -f "$scriptdir/mmfunctions" ] && { echo "Missing '$scriptdir/mmvariables' and/or '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
 
+cleanup(){
+	log -a "Process aborted"
+	exit 1
+}
+
+trap cleanup SIGHUP SIGINT SIGTERM
+log -b
+
 usage(){
     echo
 	echo "$(basename $0) ${version}"
@@ -106,3 +114,4 @@ while [ "$*" != ""  -o "$once" = "y" ] ; do
 	report -dt "STATUS ${mediaid%.*}.iso is generated."
 	shift
 done
+log -e
