adding usage summarizes, remove most use of ask_input, cleanup options

diff --git a/makebroadcast b/makebroadcast
--- a/makebroadcast
+++ b/makebroadcast
@@ -1,28 +1,45 @@
 #!/bin/bash
 # makebroadcast
 # make broadcast version
+# history
+# v 1.1 change from mov output to mxf output, force all output to hd
+# v 1.2 revert to mov and ffmbc
+version="1.2"
+unset dependencies
+dependencies=(ffmbc)
 
 scriptdir=$(dirname "$0")
 . "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
 
+usage(){
+    echo
+    echo "$(basename $0) ${version}"
+    echo "This application will create a file suitable for broadcast or editing from a video file or package input with the following options."
+    echo "Dependencies: ${dependencies[@]}"
+    echo "Usage: $(basename $0) [ -l ] [ -r ] [ -c ] fileorpackage1 [ fileorpackage2 ...]"
+    echo "  -l (only use the left channel of the first audio track)"
+    echo "  -r (only use the right channel of the first audio track)"
+    echo "  -c (run the video through a crop detection filter, then crop the video accordingly during transcoding, slower)"
+    echo "  -h display this help"
+    echo
+    exit
+}
+[ "$#" = 0 ] && usage
+check_dependencies "${dependencies[@]}"
+
 # command line arguments
 OPTIND=1
-while getopts lc opt ; do
+while getopts ":lrch" opt ; do
     case $opt in
         l) audiomapping=(-map_audio_channel 0:1:0:0:1:0 -map_audio_channel 0:1:0:0:1:1) ;;
         r) audiomapping=(-map_audio_channel 0:1:1:0:1:0 -map_audio_channel 0:1:1:0:1:1) ;;
         c) cropdetect="Y" ;;
-        f) input="$OPTARG" ; once="y" ;;
+        h) usage ;;
+        *) echo "Invalid option: -$OPTARG" ; exit 1 ;;
+        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
-
-[ "$#" = 0 -a ! "$input" ] && { ask_input ; once="y" ;};
-
-version="1.2"
-# history
-# v 1.1 change from mov output to mxf output, force all output to hd
-# v 1.2 revert to mov and ffmbc
 
 cleanup(){
     log -a "Process aborted"
@@ -31,15 +48,14 @@ cleanup(){
 
 trap cleanup SIGHUP SIGINT SIGTERM
 
-while [ "$*" != ""  -o "$once" = "y" ] ; do
-    once="n"
+while [ "$*" != "" ] ; do
     
     # clear local arrays
     unset audiomapping
     unset inputoptions
     unset ffmbc_opts
     
-    [ "$#" != 0 ] && input="$1"
+    input="$1"
     [ -d "$input" ] && { outputdir="$input/objects/service" && logdir="$input/metadata/submissionDocumentation/logs" ;};
     [ -f "$input" ] && { outputdir=$(dirname "$input")"/service" && logdir="$(dirname "$input")/service/logs" ;};
     [ ! "$outputdir" ] && { outputdir="$input/objects/service" && logdir="$input/metadata/submissionDocumentation/logs" ;};
diff --git a/makeframes b/makeframes
--- a/makeframes
+++ b/makeframes
@@ -1,9 +1,24 @@
 #!/bin/bash
+# makeframes
+version="1.0"
+unset dependencies
+dependencies=(ffmpeg)
 
 scriptdir=$(dirname "$0")
 . "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
 
-[ "$#" = 0 -a ! "$input" ] && { ask_input ; once="y" ;};
+usage(){
+    echo
+    echo "$(basename $0) ${version}"
+    echo "This application will create a series of still images from a video file or package input with the following options."
+    echo "Dependencies: ${dependencies[@]}"
+    echo "Usage: $(basename $0) fileorpackage1 [ fileorpackage2 ...]"
+    echo "  -h display this help"
+    echo
+    exit
+}
+[ "$#" = 0 ] && usage
+check_dependencies "${dependencies[@]}"
 
 # local variables
 IMAGECOUNT=10
@@ -16,19 +31,17 @@ trap cleanup SIGHUP SIGINT SIGTERM
 
 # command-line options to set mediaid and original variables
 OPTIND=1
-while getopts ":m:f:" opt; do
+while getopts ":h" opt; do
     case "$opt" in
-        m) mediaid="$OPTARG";;
-        f) input="$OPTARG" ; once="y" ;;
-        \?) echo "Invalid option: -$OPTARG" ; exit 1 ;;
+        h) usage;;
+        *) echo "Invalid option: -$OPTARG" ; exit 1 ;;
         :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
 
-while [ "$*" != ""  -o "$once" = "y" ] ; do
-    once="n"
-    [ "$#" != 0 ] && input="$1"
+while [ "$*" != "" ] ; do
+    input="$1"
     [ -d "$input" ] && { outputdir="$input/objects/access/images" && logdir="$input/metadata/submissionDocumentation/logs" ;};
     [ -f "$input" ] && { outputdir=$(dirname "$input")"/access/images" && logdir="$(dirname "$input")/access/logs" ;};
     [ ! "$outputdir" ] && { outputdir="$input/objects/access/images" && logdir="$input/metadata/submissionDocumentation/logs" ;};
diff --git a/uploadomneon b/uploadomneon
--- a/uploadomneon
+++ b/uploadomneon
@@ -1,8 +1,26 @@
 #!/bin/bash
 # uploadomneon
 # upload to omneon
+version="1.0"
+
 scriptdir=$(dirname "$0")
 . "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
+
+usage(){
+    echo
+    echo "$(basename $0) ${version}"
+    echo "This application will upload file(s) to a server via rsync in sequential order. Options are specified via 'mmconfig'."
+    echo
+    echo "Settings:"
+    echo "OMNEONIP=${OMNEONIP}"
+    echo "OMNEONPATH=${OMNEONPATH}"
+    echo "TMPDIR=${TMPDIR}"
+    echo "Usage: $(basename $0) file1 [ file2 ...]"
+    echo "  -h ( display this help )"
+    echo
+    exit
+}
+[ "$#" = 0 ] && usage
 
 cleanup(){
     log -a "Process aborted"
@@ -12,42 +30,24 @@ cleanup(){
 trap cleanup SIGHUP SIGINT SIGTERM
 log -b
 
-usage(){
-    echo
-    echo "$(basename $0) ${version}"
-    echo "This script may be run interactively by running it with no arguments or may be used with the following options."
-    echo "Usage: $(basename $0) [ -f sourcefile ] [ -i omneon_ip ] [ -n omneon_path ] [ -t tmp_dir]"
-    echo "  -f sourcefile"
-    echo "  -i omneonip"
-    echo "  -n omneonpath"
-    echo "  -t tmpdir"
-    exit
-}
-
 # command-line options to set mediaid and original variables
 OPTIND=1
-while getopts ":hm:f:t:ip" opt; do
+while getopts ":h" opt; do
     case "$opt" in
         h) usage ;;
-        f) input="$OPTARG" ; once="y" ;;
-        i) OMNEONIP="$OPTARG" ;;
-        n) OMNEONPATH="$OPTARG" ;;
-        t) TMPDIR="$OPTARG" ;;
-        \?) echo "Invalid option: -$OPTARG" ; exit 1 ;;
+        *) echo "Invalid option: -$OPTARG" ; exit 1 ;;
         :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
     esac
 done
-
-[ ! -d "$TMPDIR" ] && { echo "The temporary directory must be set. Use [ -t /path/to/temporary/directory ]." ; exit 1 ;};
-[ ! -d "$OMNEONIP"] && { echo "The Omneon IP must be set." ; exit 1 ;};
-[ ! -d "$OMNEONPATH"] && { echo "The Omneon Path must be set." ; exit 1 ;};
-
 shift $(( ${OPTIND} - 1 ))
-[ "$#" = 0 -a ! "$input" ] && { ask_input ; once="y" ;};
 
-while [ "$*" != ""  -o "$once" = "y" ] ; do
-once="n"
-[ "$#" != 0 ] && sourcefile="$1"
+[ ! -d "$TMPDIR" ] && { echo "The temporary directory must be set and be available. Run 'mmconfig'." ; exit 1 ;};
+[ ! -d "$OMNEONIP"] && { echo "The Omneon IP must be set. Run 'mmconfig'." ; exit 1 ;};
+[ ! -d "$OMNEONPATH"] && { echo "The Omneon Path must be set. Run 'mmconfig'." ; exit 1 ;};
+
+while [ "$*" != "" ] ; do
+
+sourcefile="$1"
 removetmp="n"
 filename=$(basename "$sourcefile")
 
@@ -76,9 +76,10 @@ binary
 put "$uploadfile" "${OMNEONPATH}/${filename}"
 exit
 END_SCRIPT
-report -wt "ftp exited with code ${?}"
+upload_err="${?}"
+report -wt "ftp exited with code ${upload_err}"
 report -dt "${filename} is uploaded to the omneon"
-[ "$?" = "0" ] && [ "$removetmp" = "y" ] && rm "${TMPDIR}/${filename}"
+[ "$upload_err" = "0" ] && [ "$removetmp" = "y" ] && rm "${TMPDIR}/${filename}"
 else
 size=$(echo "$status" | grep "$filename" | awk '{print $5}')
 size_g=$(echo "scale=3; $size / 1073741824" | bc)
