start moving from ffmpeg to setting a variable on where the preferred ffmpeg is

diff --git a/makeaudiographs b/makeaudiographs
--- a/makeaudiographs
+++ b/makeaudiographs
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
+
 _ss_to_hhmmss(){
     # if milliseconds are used it will round down to nearest second for instance 60.9, will return 1:00
     INT="${1%.*}"
@@ -54,7 +56,7 @@ while [[ "${@}" != "" ]] ; do
         TIMELINE+=",drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:text='${MARK_TIME}':x=${MARK_X}-text_w:y=(${HEADER_HEIGHT}-${TIMELINE_FONTSIZE})/2"
     done
 
-    ffmpeg -nostdin -y -i "$FILENAME" -filter_complex "asplit=10[e][f][g][h][i][j][k][l][m][n];\
+    "${FFMPEG_BIN}" -nostdin -y -i "$FILENAME" -filter_complex "asplit=10[e][f][g][h][i][j][k][l][m][n];\
         `#timeline`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT}${TIMELINE},split=6[top1][top2][top3][top4][top5][top6];\
         color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT_BIG},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=36:text='Audio QC Graph\:   Filename\: ${BASENAME},   Duration\: $(_ss_to_hhmmss "${DURATION}"),   Audio Frame Size\: ${AUDIO_FRAME_SIZE}'[Header];\
         `#int_loudnorm`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=24:text='Interstitial (with loudnorm) -1...1. Differences in readings from sample to sample. May indicate dropped samples.'[intAH];\
