initial commit for db error/log function

diff --git a/mmfunctions b/mmfunctions
--- a/mmfunctions
+++ b/mmfunctions
@@ -61,6 +61,32 @@ _report_to_db(){
 fi
 }
 
+_db_error_check(){
+
+if [ "$?" != "0" ]; then
+    echo -e "\033[1;5;95mERROR:\033[0m \033[1;93mCould not access database "$PREMIS_NAME".  Information was not added to table "$table_name". SQL command history has been written to "$MEDIAID"_dbreport.txt\033[0m"
+    
+    if [ "$table_name" = "object" ] ; then
+    echo "\"INSERT IGNORE INTO object (objectIdentifierValue) VALUES ('$MEDIAID')\" | mysql --login-path=\"$PREMIS_PROFILE\"  \"$PREMIS_NAME\"" > ~/Desktop/"$MEDIAID"_dbreport.txt
+    fi
+    
+    if [ "$table_name" = "fixity" ] ; then
+        IFS=$(echo -en "\n\b")
+        for i in ${db_fixity}; do LINE=$i;
+        messageDigestHASH=$(echo "$LINE" | cut -c -32 )
+        messageDigestPATH=$(echo "$LINE" | cut -c 35- )
+        messageDigestFILENAME=$(basename ${messageDigestPATH})
+        echo "\"INSERT INTO fixity (objectIdentifierValue,eventDetail,messageDigestAlgorithm,messageDigestPATH,messageDigestFILENAME,messageDigestHASH) VALUES ('$MEDIAID','$eventDetail','md5','$messageDigestPATH','$messageDigestFILENAME','$messageDigestHASH')\" | mysql --login-path=\"$PREMIS_PROFILE\" \"$PREMIS_NAME\"" >> ~/Desktop/"$MEDIAID"_dbreport.txt
+        done
+        unset IFS
+    fi
+    
+    if [ "$table_name" = "event" ] ; then
+    echo "\"INSERT INTO event (objectIdentifierValue,eventType,eventDetail,eventDetailOPT,eventDetailCOMPNAME,linkingAgentIdentifierValue) VALUES ('$MEDIAID','$eventType','$eventDetail','$user_input','$HOSTNAME', '$OP')\" | mysql --login-path=\"$PREMIS_PROFILE\"  \"$PREMIS_NAME\"" >> ~/Desktop/"$MEDIAID"_dbreport.txt
+    fi
+fi
+}
+
 
 
 _premis_event_list(){
