change all `` to $()

diff --git a/mmfunctions b/mmfunctions
--- a/mmfunctions
+++ b/mmfunctions
@@ -1,5 +1,5 @@
 # assign variables
-SCRIPTNAME=`basename "$0"`
+SCRIPTNAME=$(basename "$0")
 CONFIG_FILE="$scriptdir/mm.conf"
 WHAT_IS_THIS="mediamicroservices"
 
@@ -33,7 +33,7 @@ log(){
     done
     shift $(( ${OPTIND} - 1 ))
     note="$1"
-    echo `get_iso8601`", $(basename $0), $status, $op, $mediaid, $note" >> "$logfile"
+    echo $(get_iso8601)", $(basename $0), $status, $op, $mediaid, $note" >> "$logfile"
 }
 
 report(){
@@ -64,21 +64,21 @@ report(){
 
 black_at_ends(){
     input_movie="$1"
-    name=`basename "$input_movie"`
+    name=$(basename "$input_movie")
     analysis_head_seconds=10
     analysis_tail_seconds=10
     report -dt "Analyzing $name for excessive black at head or tail."
-    duration=`ffprobe "$1"  -show_format 2> /dev/null | grep duration | cut -d= -f2 | cut -d. -f1`
-    tail_start=`echo "$duration - $analysis_tail_seconds" | bc`
-    head_black=`ffmpeg -t "$analysis_head_seconds" -i "$1" -an -vf blackdetect=pix_th=0.05 -loglevel debug -f null - 2>&1 | grep -c -o picture_black_ratio:1`
+    duration=$(ffprobe "$1"  -show_format 2> /dev/null | grep duration | cut -d= -f2 | cut -d. -f1)
+    tail_start=$(echo "$duration - $analysis_tail_seconds" | bc)
+    head_black=$(ffmpeg -t "$analysis_head_seconds" -i "$1" -an -vf blackdetect=pix_th=0.05 -loglevel debug -f null - 2>&1 | grep -c -o picture_black_ratio:1)
     report -dt "Black frames in first $analysis_head_seconds seconds: $head_black."
-    tail_black=`ffmpeg -ss "$tail_start" -i "$1" -an -vf blackdetect=pix_th=0.05 -loglevel debug -f null - 2>&1 | grep -c -o picture_black_ratio:1`
+    tail_black=$(ffmpeg -ss "$tail_start" -i "$1" -an -vf blackdetect=pix_th=0.05 -loglevel debug -f null - 2>&1 | grep -c -o picture_black_ratio:1)
     report -dt "Black frames in last  $analysis_head_seconds seconds: $tail_black."
 }
 
 maketemp(){
-    tempfoo=`basename $0`
-    TMPFILE=`mktemp -q /tmp/${tempfoo}.XXXXXX`
+    tempfoo=$(basename $0)
+    TMPFILE=$(mktemp -q /tmp/${tempfoo}.XXXXXX)
     if [ $? -ne 0 ]; then
         echo "$0: Can't create temp file, exiting..."
         exit 1
@@ -103,7 +103,7 @@ ask_mediaid(){
         [ "$mediaid" == "q" ] && exit 0
         # validate id and perhaps fail with exit
         [ -z "$mediaid" ] && report -wt "ERROR You must enter a valid MEDIA ID" && exit
-        [ ! -z `echo "$mediaid" | grep -v "^[A-Z0-9_-]*$"` ] && report -wt "ERROR The MEDIA ID must only contain capital letters, letters, hyphen and underscore" && exit 1
+        [ ! -z $(echo "$mediaid" | grep -v "^[A-Z0-9_-]*$") ] && report -wt "ERROR The MEDIA ID must only contain capital letters, letters, hyphen and underscore" && exit 1
     fi
     [ ! -z "$mediaid" ] && log+="mediaid: ${mediaid}\n"
 }
@@ -114,7 +114,7 @@ ask_input(){
         read input
         [ -z "$input" ] && ask_input
         [ "$input" == "q" ] && exit 0
-        basename=`basename "$input"`
+        basename=$(basename "$input")
         [ ! -z "$input log" ] && log+="input: ${input}\n"
     fi
 }
@@ -175,47 +175,47 @@ make_mezz_for_xdcam(){
     som="$1"
     dur="$2"
 
-    tmc_ms=`mediainfo --inform="Video;%Delay%" "$3"`
-    tmc_smp=`mediainfo --inform="Video;%Delay/String3%" "$3"`
-    tmc_sec=`echo "$tmc_ms * 0.001" | bc`
+    tmc_ms=$(mediainfo --inform="Video;%Delay%" "$3")
+    tmc_smp=$(mediainfo --inform="Video;%Delay/String3%" "$3")
+    tmc_sec=$(echo "$tmc_ms * 0.001" | bc)
 
-    som_h=`echo "$som" | cut -c 1-2`
-    som_m=`echo "$som" | cut -c 4-5`
-    som_s=`echo "$som" | cut -c 7-8`
-    som_f=`echo "$som" | cut -c 10-11`
-    som_fc=`echo "scale=3; (((((3600 * $som_h)+(60 * $som_m)+ $som_s ) * 30)+ $som_f ) - ( 2 * (((60 * $som_h)+ $som_m ) - (((60 * $som_h)+ $som_m ) / 10 )))) / 29.97" | bc`
+    som_h=$(echo "$som" | cut -c 1-2)
+    som_m=$(echo "$som" | cut -c 4-5)
+    som_s=$(echo "$som" | cut -c 7-8)
+    som_f=$(echo "$som" | cut -c 10-11)
+    som_fc=$(echo "scale=3; (((((3600 * $som_h)+(60 * $som_m)+ $som_s ) * 30)+ $som_f ) - ( 2 * (((60 * $som_h)+ $som_m ) - (((60 * $som_h)+ $som_m ) / 10 )))) / 29.97" | bc)
 
-    dur_h=`echo "$dur" | cut -c 1-2`
-    dur_m=`echo "$dur" | cut -c 4-5`
-    dur_s=`echo "$dur" | cut -c 7-8`
-    dur_f=`echo "$dur" | cut -c 10-11`
-    dur_fc=`echo "scale=3; (((((3600 * $dur_h)+(60 * $dur_m)+ $dur_s ) * 30)+ $dur_f ) - ( 2 * (((60 * $dur_h)+ $dur_m ) - (((60 * $dur_h)+ $dur_m ) / 10 )))) / 29.97" | bc`
+    dur_h=$(echo "$dur" | cut -c 1-2)
+    dur_m=$(echo "$dur" | cut -c 4-5)
+    dur_s=$(echo "$dur" | cut -c 7-8)
+    dur_f=$(echo "$dur" | cut -c 10-11)
+    dur_fc=$(echo "scale=3; (((((3600 * $dur_h)+(60 * $dur_m)+ $dur_s ) * 30)+ $dur_f ) - ( 2 * (((60 * $dur_h)+ $dur_m ) - (((60 * $dur_h)+ $dur_m ) / 10 )))) / 29.97" | bc)
 
-    rel_start=`echo "scale=3; $som_fc - $tmc_sec" | bc`
-    pushd `dirname "$4"`
-    report -dt "Starting ffmpeg to trim mxf file at `date`. This will take a few minutes..."
+    rel_start=$(echo "scale=3; $som_fc - $tmc_sec" | bc)
+    pushd $(dirname "$4")
+    report -dt "Starting ffmpeg to trim mxf file at $(date) This will take a few minutes..."
     ffmpeg 2</dev/null -report -y -ss "$rel_start" -t "$dur_fc" -i "$3" -map 0:v -map 0:a:0 -map 0:a:1 -c copy "$4"
     popd
 }
 
 find_input (){
-    [ -d "$1" ] && [ -d "$1/objects/service" ] && sourcefile=`find "$1/objects/service" -maxdepth 1 -mindepth 1 -type f \( -name "*.mov" -o -name "*.mxf" -o -name "*.mp4" -o -name "*.dv" \) ! -name ".*"`
+    [ -d "$1" ] && [ -d "$1/objects/service" ] && sourcefile=$(find "$1/objects/service" -maxdepth 1 -mindepth 1 -type f \( -name "*.mov" -o -name "*.mxf" -o -name "*.mp4" -o -name "*.dv" \) ! -name ".*")
     [ -f "$1" ] && sourcefile="$1"
-    [ ! "$sourcefile" ] && sourcefile=`find "$1/objects" -maxdepth 1 -mindepth 1 -type f \( -name "*.mov" -o -name "*.mxf" -o -name "*.mp4" -o -name "*.dv" \) ! -name ".*"`
+    [ ! "$sourcefile" ] && sourcefile=$(find "$1/objects" -maxdepth 1 -mindepth 1 -type f \( -name "*.mov" -o -name "*.mxf" -o -name "*.mp4" -o -name "*.dv" \) ! -name ".*")
     [ ! "$sourcefile" ] && { report -wt "A valid source file isn't found." ; exit 1 ;};
     log+="sourcefile: ${sourcefile}\n"
 }
 
 get_width(){
-    width=`ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep width= | cut -d = -f 2`
+    width=$(ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep width= | cut -d = -f 2)
 }
 
 get_height(){
-    height=`ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep height= | cut -d = -f 2`
+    height=$(ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep height= | cut -d = -f 2)
 }
 
 get_dar(){
-    dar=`ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep display_aspect_ratio= | cut -d = -f 2 | sed 's|:|/|g'`
+    dar=$(ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep display_aspect_ratio= | cut -d = -f 2 | sed 's|:|/|g')
     if [ "$dar" = "0/1" ] ; then
         get_width "$1"
         get_height "$1"
@@ -224,18 +224,18 @@ get_dar(){
 }
 
 get_codectagstring(){
-    codec_tag_string=`ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep codec_tag_string= | cut -d = -f 2`
+    codec_tag_string=$(ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep codec_tag_string= | cut -d = -f 2)
 }
 
 get_duration(){
-    DURATION=`ffprobe "$1" -show_format 2> /dev/null | grep duration= | cut -d = -f 2`
+    DURATION=$(ffprobe "$1" -show_format 2> /dev/null | grep duration= | cut -d = -f 2)
 }
 
 get_maxdvdbitrate(){
     get_duration "$1"
     local DVDCAPACITY=37000000000  # in bits
     local CAPDVDBITRATE=6000000    # in bits/second
-    MAXDVDBITRATE=`echo "(37000000000 - ( $DURATION * 224000 )) / $DURATION" | bc`
+    MAXDVDBITRATE=$(echo "(37000000000 - ( $DURATION * 224000 )) / $DURATION" | bc)
     if ! [[ "$MAXDVDBITRATE" =~ ^[0-9]+$ ]] ; then
         report -wt "Calculation of dvd bitrate failed. Evaluated to ${MAXDVDBITRATE}. Using 4000000 as bitrate instead."
         MAXDVDBITRATE=4000000
@@ -255,14 +255,14 @@ get_volume_adjustment(){
     reference=-23
     input_movie="$1"
     report -dt "Getting volume data for $(basename "$input_movie") ..."
-    volume_data=`ffprobe -v error -of compact=p=0:nk=1 -show_entries frame=metadata:tags=lavfi.r128.I -f lavfi "amovie='${input_movie}',ebur128=metadata=1"`
+    volume_data=$(ffprobe -v error -of compact=p=0:nk=1 -show_entries frame=metadata:tags=lavfi.r128.I -f lavfi "amovie='${input_movie}',ebur128=metadata=1")
     [ $? -ne 0 ] && { report -wt "Volume analysis for $input_movie exited with $?." ; exit ;};
     for i in $(echo "$volume_data" | xargs); do
         [ "$i" != "" ] && integrated_loudness="$i"
     done
-    VOLADJ=`echo "$reference - $integrated_loudness" | bc`
+    VOLADJ=$(echo "$reference - $integrated_loudness" | bc)
     # test to see if adjustment is at least 1dB, else skip
-    if [ `echo "$VOLADJ < 1" |bc` -eq 1 -a `echo "$VOLADJ > -1" |bc` -eq 1 ] ; then
+    if [ $(echo "$VOLADJ < 1" |bc) -eq 1 -a $(echo "$VOLADJ > -1" |bc) -eq 1 ] ; then
         report -dt "Integrated loudness for $name is ${integrated_loudness}dB. Reference is ${reference}dB. No adjustment is needed for ${name}, skipping."
         VOLADJ=""
     else
@@ -273,7 +273,7 @@ get_volume_adjustment(){
 get_cropdetection(){
     input_movie="$1"
     report -dt "Getting cropping data for $(basename "$input_movie") ..."
-    crop_data=`ffmpeg -i "${input_movie}" -an -vf cropdetect -f null - 2>&1 | grep -o "crop=[0-9:]*"`
+    crop_data=$(ffmpeg -i "${input_movie}" -an -vf cropdetect -f null - 2>&1 | grep -o "crop=[0-9:]*")
     crop_err="$?"
     [ "$crop_err" -ne 0 ] && { report -wt "Crop detection analysis for $input_movie exited with $crop_err." ; exit ;};
     for i in $(echo "$crop_data" | xargs); do
@@ -288,7 +288,7 @@ free_space(){
     local outputdir="$2"
     [ ! -d "$outputdir" ] && { report -wt "The output directory [$outputdir] that free-space function is seeking does not exist." ; exit 1 ;};
     [[ ! $space =~ ^-?[0-9]+$ ]] && { report -wt "Number is not an integer." ; exit 1 ;};
-    freespace=`df -g "$outputdir" | awk '{ print $4; }' | tail -n 1`
+    freespace=$(df -g "$outputdir" | awk '{ print $4; }' | tail -n 1)
     if [ $freespace -lt $space ]; then
       report -wts "ERROR only $freespace gb free in this directory. This script requires at least $space gigabytes"
       exit 1
