results and check on input

diff --git a/searchfingerprint b/searchfingerprint
--- a/searchfingerprint
+++ b/searchfingerprint
@@ -27,10 +27,29 @@ while [ "${*}" != "" ] ; do
     IO=$(mktemp)
     TEMPFINGERPRINT=$(mktemp)
     TEMPFINGERPRINT_SORTED=$(mktemp)
+    RESULTS=$(mktemp)
     echo "file '${INPUT}'" > "${IO}"
-    echo "inpoint ${INTIME}" >> "${IO}"
-    echo "outpoint ${OUTTIME}" >> "${IO}"
+    if [ -n "${INTIME}" ] ; then
+        echo "inpoint ${INTIME}" >> "${IO}"
+    fi
+    if [ -n "${OUTTIME}" ]; then
+        if [ -n "${INTIME}" ] && ! [ "${OUTTIME}" -gt "${INTIME}" ] ; then
+            echo "Error! Output time must be greater than input time!" && exit 1
+        else 
+            echo "outpoint ${OUTTIME}" >> "${IO}"
+        fi
+    fi
     ffmpeg -f concat -safe 0 -i "${IO}" -vf signature=format=xml:filename="${TEMPFINGERPRINT}" -map 0:v -f null -
-    xml sel -N "m=urn:mpeg:mpeg7:schema:2001" -t -m "m:Mpeg7/m:DescriptionUnit/m:Descriptor/m:VideoSignatureRegion/m:VSVideoSegment" -v m:StartFrameOfSegment -o ':' -v m:EndFrameOfSegment -o ':' -m m:BagOfWords -v "translate(.,' ','')" -o ':' -b -n "${TEMPFINGERPRINT}"
+    xml sel -N "m=urn:mpeg:mpeg7:schema:2001" -t -m "m:Mpeg7/m:DescriptionUnit/m:Descriptor/m:VideoSignatureRegion/m:VSVideoSegment" -v m:StartFrameOfSegment -o ':' -v m:EndFrameOfSegment -o ':' -m m:BagOfWords -v "translate(.,' ','')" -o ':' -b -n "${TEMPFINGERPRINT}" > "${TEMPFINGERPRINT_SORTED}"
     
+    (IFS=$'\n'
+    for i in $(cat "${TEMPFINGERPRINT_SORTED}") ; do
+        hash1=$(echo "${i}" | cut -d':' -f3)
+        hash2=$(echo "${i}" | cut -d':' -f4)
+        hash3=$(echo "${i}" | cut -d':' -f5)
+        hash4=$(echo "${i}" | cut -d':' -f6)
+        echo "SELECT objectIdentifierValue,startframe,endframe FROM fingerprints WHERE hash1='${hash1}' AND hash2='${hash2}' AND (hash3='${hash3}' OR hash4='${hash4}')" | mysql --login-path="${PREMIS_PROFILE}"  "${PREMIS_NAME}" >> "${RESULTS}"
+    done)
+    echo "The Following potential matches were found:"
+    cat "${RESULTS}" | sort -u
 done
