Added option for xdcam ingest file

diff --git a/xdcamingest b/xdcamingest
--- a/xdcamingest
+++ b/xdcamingest
@@ -6,6 +6,27 @@ scriptdir=`dirname "$0"`
 . "$scriptdir/functions"
 [ ! -f "$scriptdir/variables" -o ! -f "$scriptdir/functions" ] && { echo "Missing '$scriptdir/variables' and/or '$scriptdir/functions'. Exiting." ; exit 1 ;};
 
+usage(){
+    echo
+	echo "$(basename $0) ${version}"
+	echo "This script may be run interactively by running it with no arguments or may be used with the following options."
+	echo "Usage: $(basename $0) [ -c ingest_xd_cam ]"
+	echo "  -c ingestxdcam"
+	exit
+}
+
+# command-line options to set mediaid and original variables
+while getopts ":hm:f:p:a:w:y:x" opt; do
+	case "$opt" in
+		h) usage ;;
+		c) OUTDIR_INGESTXDCAM="$OPTARG" ;;
+		\?) echo "Invalid option: -$OPTARG" ; exit 1 ;;
+		:) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
+	esac
+done
+
+[ ! -d "$OUTDIR_INGESTXDCAM" ] && echo "The XD Cam processing directory must be set. Use [ -p /path/to/XDCam/processing/directory ]." && exit 1
+
 defaults write com.apple.desktopservices DSDontWriteNetworkStores true
 
 while true ; do
